// Generated by jextract

package org.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class __arm_legacy_debug_state {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(16, Constants$root.C_INT$LAYOUT).withName("__bvr"),
        MemoryLayout.sequenceLayout(16, Constants$root.C_INT$LAYOUT).withName("__bcr"),
        MemoryLayout.sequenceLayout(16, Constants$root.C_INT$LAYOUT).withName("__wvr"),
        MemoryLayout.sequenceLayout(16, Constants$root.C_INT$LAYOUT).withName("__wcr")
    ).withName("__arm_legacy_debug_state");
    public static MemoryLayout $LAYOUT() {
        return __arm_legacy_debug_state.$struct$LAYOUT;
    }
    public static MemorySegment __bvr$slice(MemorySegment seg) {
        return seg.asSlice(0, 64);
    }
    public static MemorySegment __bcr$slice(MemorySegment seg) {
        return seg.asSlice(64, 64);
    }
    public static MemorySegment __wvr$slice(MemorySegment seg) {
        return seg.asSlice(128, 64);
    }
    public static MemorySegment __wcr$slice(MemorySegment seg) {
        return seg.asSlice(192, 64);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


