// Generated by jextract

package org.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class __darwin_arm_vfp_state {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(64, Constants$root.C_INT$LAYOUT).withName("__r"),
        Constants$root.C_INT$LAYOUT.withName("__fpscr")
    ).withName("__darwin_arm_vfp_state");
    public static MemoryLayout $LAYOUT() {
        return __darwin_arm_vfp_state.$struct$LAYOUT;
    }
    public static MemorySegment __r$slice(MemorySegment seg) {
        return seg.asSlice(0, 256);
    }
    static final VarHandle __fpscr$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("__fpscr"));
    public static VarHandle __fpscr$VH() {
        return __darwin_arm_vfp_state.__fpscr$VH;
    }
    public static int __fpscr$get(MemorySegment seg) {
        return (int)__darwin_arm_vfp_state.__fpscr$VH.get(seg);
    }
    public static void __fpscr$set( MemorySegment seg, int x) {
        __darwin_arm_vfp_state.__fpscr$VH.set(seg, x);
    }
    public static int __fpscr$get(MemorySegment seg, long index) {
        return (int)__darwin_arm_vfp_state.__fpscr$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void __fpscr$set(MemorySegment seg, long index, int x) {
        __darwin_arm_vfp_state.__fpscr$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


