// Generated by jextract

package org.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class __darwin_arm_neon_state {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(16, MemoryLayout.paddingLayout(128).withName("__int128")).withName("__v"),
        Constants$root.C_INT$LAYOUT.withName("__fpsr"),
        Constants$root.C_INT$LAYOUT.withName("__fpcr"),
        MemoryLayout.paddingLayout(64)
    ).withName("__darwin_arm_neon_state");
    public static MemoryLayout $LAYOUT() {
        return __darwin_arm_neon_state.$struct$LAYOUT;
    }
    static final VarHandle __fpsr$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("__fpsr"));
    public static VarHandle __fpsr$VH() {
        return __darwin_arm_neon_state.__fpsr$VH;
    }
    public static int __fpsr$get(MemorySegment seg) {
        return (int)__darwin_arm_neon_state.__fpsr$VH.get(seg);
    }
    public static void __fpsr$set( MemorySegment seg, int x) {
        __darwin_arm_neon_state.__fpsr$VH.set(seg, x);
    }
    public static int __fpsr$get(MemorySegment seg, long index) {
        return (int)__darwin_arm_neon_state.__fpsr$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void __fpsr$set(MemorySegment seg, long index, int x) {
        __darwin_arm_neon_state.__fpsr$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle __fpcr$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("__fpcr"));
    public static VarHandle __fpcr$VH() {
        return __darwin_arm_neon_state.__fpcr$VH;
    }
    public static int __fpcr$get(MemorySegment seg) {
        return (int)__darwin_arm_neon_state.__fpcr$VH.get(seg);
    }
    public static void __fpcr$set( MemorySegment seg, int x) {
        __darwin_arm_neon_state.__fpcr$VH.set(seg, x);
    }
    public static int __fpcr$get(MemorySegment seg, long index) {
        return (int)__darwin_arm_neon_state.__fpcr$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void __fpcr$set(MemorySegment seg, long index, int x) {
        __darwin_arm_neon_state.__fpcr$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


