// Generated by jextract

package org.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class attrreference {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("attr_dataoffset"),
        Constants$root.C_INT$LAYOUT.withName("attr_length")
    ).withName("attrreference");
    public static MemoryLayout $LAYOUT() {
        return attrreference.$struct$LAYOUT;
    }
    static final VarHandle attr_dataoffset$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("attr_dataoffset"));
    public static VarHandle attr_dataoffset$VH() {
        return attrreference.attr_dataoffset$VH;
    }
    public static int attr_dataoffset$get(MemorySegment seg) {
        return (int)attrreference.attr_dataoffset$VH.get(seg);
    }
    public static void attr_dataoffset$set( MemorySegment seg, int x) {
        attrreference.attr_dataoffset$VH.set(seg, x);
    }
    public static int attr_dataoffset$get(MemorySegment seg, long index) {
        return (int)attrreference.attr_dataoffset$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void attr_dataoffset$set(MemorySegment seg, long index, int x) {
        attrreference.attr_dataoffset$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle attr_length$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("attr_length"));
    public static VarHandle attr_length$VH() {
        return attrreference.attr_length$VH;
    }
    public static int attr_length$get(MemorySegment seg) {
        return (int)attrreference.attr_length$VH.get(seg);
    }
    public static void attr_length$set( MemorySegment seg, int x) {
        attrreference.attr_length$VH.set(seg, x);
    }
    public static int attr_length$get(MemorySegment seg, long index) {
        return (int)attrreference.attr_length$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void attr_length$set(MemorySegment seg, long index, int x) {
        attrreference.attr_length$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


