// Generated by jextract

package org.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class attribute_set {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("commonattr"),
        Constants$root.C_INT$LAYOUT.withName("volattr"),
        Constants$root.C_INT$LAYOUT.withName("dirattr"),
        Constants$root.C_INT$LAYOUT.withName("fileattr"),
        Constants$root.C_INT$LAYOUT.withName("forkattr")
    ).withName("attribute_set");
    public static MemoryLayout $LAYOUT() {
        return attribute_set.$struct$LAYOUT;
    }
    static final VarHandle commonattr$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("commonattr"));
    public static VarHandle commonattr$VH() {
        return attribute_set.commonattr$VH;
    }
    public static int commonattr$get(MemorySegment seg) {
        return (int)attribute_set.commonattr$VH.get(seg);
    }
    public static void commonattr$set( MemorySegment seg, int x) {
        attribute_set.commonattr$VH.set(seg, x);
    }
    public static int commonattr$get(MemorySegment seg, long index) {
        return (int)attribute_set.commonattr$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void commonattr$set(MemorySegment seg, long index, int x) {
        attribute_set.commonattr$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle volattr$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("volattr"));
    public static VarHandle volattr$VH() {
        return attribute_set.volattr$VH;
    }
    public static int volattr$get(MemorySegment seg) {
        return (int)attribute_set.volattr$VH.get(seg);
    }
    public static void volattr$set( MemorySegment seg, int x) {
        attribute_set.volattr$VH.set(seg, x);
    }
    public static int volattr$get(MemorySegment seg, long index) {
        return (int)attribute_set.volattr$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void volattr$set(MemorySegment seg, long index, int x) {
        attribute_set.volattr$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle dirattr$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("dirattr"));
    public static VarHandle dirattr$VH() {
        return attribute_set.dirattr$VH;
    }
    public static int dirattr$get(MemorySegment seg) {
        return (int)attribute_set.dirattr$VH.get(seg);
    }
    public static void dirattr$set( MemorySegment seg, int x) {
        attribute_set.dirattr$VH.set(seg, x);
    }
    public static int dirattr$get(MemorySegment seg, long index) {
        return (int)attribute_set.dirattr$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void dirattr$set(MemorySegment seg, long index, int x) {
        attribute_set.dirattr$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle fileattr$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("fileattr"));
    public static VarHandle fileattr$VH() {
        return attribute_set.fileattr$VH;
    }
    public static int fileattr$get(MemorySegment seg) {
        return (int)attribute_set.fileattr$VH.get(seg);
    }
    public static void fileattr$set( MemorySegment seg, int x) {
        attribute_set.fileattr$VH.set(seg, x);
    }
    public static int fileattr$get(MemorySegment seg, long index) {
        return (int)attribute_set.fileattr$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void fileattr$set(MemorySegment seg, long index, int x) {
        attribute_set.fileattr$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle forkattr$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("forkattr"));
    public static VarHandle forkattr$VH() {
        return attribute_set.forkattr$VH;
    }
    public static int forkattr$get(MemorySegment seg) {
        return (int)attribute_set.forkattr$VH.get(seg);
    }
    public static void forkattr$set( MemorySegment seg, int x) {
        attribute_set.forkattr$VH.set(seg, x);
    }
    public static int forkattr$get(MemorySegment seg, long index) {
        return (int)attribute_set.forkattr$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void forkattr$set(MemorySegment seg, long index, int x) {
        attribute_set.forkattr$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


