// Generated by jextract

package org.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class au_expire_after {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG_LONG$LAYOUT.withName("age"),
        Constants$root.C_LONG_LONG$LAYOUT.withName("size"),
        Constants$root.C_CHAR$LAYOUT.withName("op_type"),
        MemoryLayout.paddingLayout(56)
    ).withName("au_expire_after");
    public static MemoryLayout $LAYOUT() {
        return au_expire_after.$struct$LAYOUT;
    }
    static final VarHandle age$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("age"));
    public static VarHandle age$VH() {
        return au_expire_after.age$VH;
    }
    public static long age$get(MemorySegment seg) {
        return (long)au_expire_after.age$VH.get(seg);
    }
    public static void age$set( MemorySegment seg, long x) {
        au_expire_after.age$VH.set(seg, x);
    }
    public static long age$get(MemorySegment seg, long index) {
        return (long)au_expire_after.age$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void age$set(MemorySegment seg, long index, long x) {
        au_expire_after.age$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle size$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("size"));
    public static VarHandle size$VH() {
        return au_expire_after.size$VH;
    }
    public static long size$get(MemorySegment seg) {
        return (long)au_expire_after.size$VH.get(seg);
    }
    public static void size$set( MemorySegment seg, long x) {
        au_expire_after.size$VH.set(seg, x);
    }
    public static long size$get(MemorySegment seg, long index) {
        return (long)au_expire_after.size$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void size$set(MemorySegment seg, long index, long x) {
        au_expire_after.size$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle op_type$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("op_type"));
    public static VarHandle op_type$VH() {
        return au_expire_after.op_type$VH;
    }
    public static byte op_type$get(MemorySegment seg) {
        return (byte)au_expire_after.op_type$VH.get(seg);
    }
    public static void op_type$set( MemorySegment seg, byte x) {
        au_expire_after.op_type$VH.set(seg, x);
    }
    public static byte op_type$get(MemorySegment seg, long index) {
        return (byte)au_expire_after.op_type$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void op_type$set(MemorySegment seg, long index, byte x) {
        au_expire_after.op_type$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


