// Generated by jextract

package org.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class au_mask {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("am_success"),
        Constants$root.C_INT$LAYOUT.withName("am_failure")
    ).withName("au_mask");
    public static MemoryLayout $LAYOUT() {
        return au_mask.$struct$LAYOUT;
    }
    static final VarHandle am_success$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("am_success"));
    public static VarHandle am_success$VH() {
        return au_mask.am_success$VH;
    }
    public static int am_success$get(MemorySegment seg) {
        return (int)au_mask.am_success$VH.get(seg);
    }
    public static void am_success$set( MemorySegment seg, int x) {
        au_mask.am_success$VH.set(seg, x);
    }
    public static int am_success$get(MemorySegment seg, long index) {
        return (int)au_mask.am_success$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void am_success$set(MemorySegment seg, long index, int x) {
        au_mask.am_success$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle am_failure$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("am_failure"));
    public static VarHandle am_failure$VH() {
        return au_mask.am_failure$VH;
    }
    public static int am_failure$get(MemorySegment seg) {
        return (int)au_mask.am_failure$VH.get(seg);
    }
    public static void am_failure$set( MemorySegment seg, int x) {
        au_mask.am_failure$VH.set(seg, x);
    }
    public static int am_failure$get(MemorySegment seg, long index) {
        return (int)au_mask.am_failure$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void am_failure$set(MemorySegment seg, long index, int x) {
        au_mask.am_failure$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


