// Generated by jextract

package org.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class au_tid {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("port"),
        Constants$root.C_INT$LAYOUT.withName("machine")
    ).withName("au_tid");
    public static MemoryLayout $LAYOUT() {
        return au_tid.$struct$LAYOUT;
    }
    static final VarHandle port$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("port"));
    public static VarHandle port$VH() {
        return au_tid.port$VH;
    }
    public static int port$get(MemorySegment seg) {
        return (int)au_tid.port$VH.get(seg);
    }
    public static void port$set( MemorySegment seg, int x) {
        au_tid.port$VH.set(seg, x);
    }
    public static int port$get(MemorySegment seg, long index) {
        return (int)au_tid.port$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void port$set(MemorySegment seg, long index, int x) {
        au_tid.port$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle machine$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("machine"));
    public static VarHandle machine$VH() {
        return au_tid.machine$VH;
    }
    public static int machine$get(MemorySegment seg) {
        return (int)au_tid.machine$VH.get(seg);
    }
    public static void machine$set( MemorySegment seg, int x) {
        au_tid.machine$VH.set(seg, x);
    }
    public static int machine$get(MemorySegment seg, long index) {
        return (int)au_tid.machine$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void machine$set(MemorySegment seg, long index, int x) {
        au_tid.machine$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


