// Generated by jextract

package org.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class auditinfo {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("ai_auid"),
        MemoryLayout.structLayout(
            Constants$root.C_INT$LAYOUT.withName("am_success"),
            Constants$root.C_INT$LAYOUT.withName("am_failure")
        ).withName("ai_mask"),
        MemoryLayout.structLayout(
            Constants$root.C_INT$LAYOUT.withName("port"),
            Constants$root.C_INT$LAYOUT.withName("machine")
        ).withName("ai_termid"),
        Constants$root.C_INT$LAYOUT.withName("ai_asid")
    ).withName("auditinfo");
    public static MemoryLayout $LAYOUT() {
        return auditinfo.$struct$LAYOUT;
    }
    static final VarHandle ai_auid$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("ai_auid"));
    public static VarHandle ai_auid$VH() {
        return auditinfo.ai_auid$VH;
    }
    public static int ai_auid$get(MemorySegment seg) {
        return (int)auditinfo.ai_auid$VH.get(seg);
    }
    public static void ai_auid$set( MemorySegment seg, int x) {
        auditinfo.ai_auid$VH.set(seg, x);
    }
    public static int ai_auid$get(MemorySegment seg, long index) {
        return (int)auditinfo.ai_auid$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void ai_auid$set(MemorySegment seg, long index, int x) {
        auditinfo.ai_auid$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment ai_mask$slice(MemorySegment seg) {
        return seg.asSlice(4, 8);
    }
    public static MemorySegment ai_termid$slice(MemorySegment seg) {
        return seg.asSlice(12, 8);
    }
    static final VarHandle ai_asid$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("ai_asid"));
    public static VarHandle ai_asid$VH() {
        return auditinfo.ai_asid$VH;
    }
    public static int ai_asid$get(MemorySegment seg) {
        return (int)auditinfo.ai_asid$VH.get(seg);
    }
    public static void ai_asid$set( MemorySegment seg, int x) {
        auditinfo.ai_asid$VH.set(seg, x);
    }
    public static int ai_asid$get(MemorySegment seg, long index) {
        return (int)auditinfo.ai_asid$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void ai_asid$set(MemorySegment seg, long index, int x) {
        auditinfo.ai_asid$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


