// Generated by jextract

package org.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$41 {

    static final MemoryAddress SIG_HOLD$ADDR = MemoryAddress.ofLong(5L);
    static final MemoryAddress SIG_ERR$ADDR = MemoryAddress.ofLong(-1L);
    static final MemoryAddress BADSIG$ADDR = MemoryAddress.ofLong(-1L);
    static final MemorySegment AUDITDEV_FILENAME$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("audit");
    static final MemoryAddress NOCRED$ADDR = MemoryAddress.ofLong(0L);
    static final MemoryAddress FSCRED$ADDR = MemoryAddress.ofLong(-1L);
}


