// Generated by jextract

package org.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$9 {

    static final FunctionDescriptor fuse_pollhandle_destroy$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fuse_pollhandle_destroy$MH = RuntimeHelper.downcallHandle(
        "fuse_pollhandle_destroy",
        constants$9.fuse_pollhandle_destroy$FUNC
    );
    static final FunctionDescriptor fuse_buf_size$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fuse_buf_size$MH = RuntimeHelper.downcallHandle(
        "fuse_buf_size",
        constants$9.fuse_buf_size$FUNC
    );
    static final FunctionDescriptor fuse_buf_copy$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle fuse_buf_copy$MH = RuntimeHelper.downcallHandle(
        "fuse_buf_copy",
        constants$9.fuse_buf_copy$FUNC
    );
    static final FunctionDescriptor fuse_set_signal_handlers$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fuse_set_signal_handlers$MH = RuntimeHelper.downcallHandle(
        "fuse_set_signal_handlers",
        constants$9.fuse_set_signal_handlers$FUNC
    );
    static final FunctionDescriptor fuse_remove_signal_handlers$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fuse_remove_signal_handlers$MH = RuntimeHelper.downcallHandle(
        "fuse_remove_signal_handlers",
        constants$9.fuse_remove_signal_handlers$FUNC
    );
    static final FunctionDescriptor open$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle open$MH = RuntimeHelper.downcallHandleVariadic(
        "open",
        constants$9.open$FUNC
    );
}


