// Generated by jextract

package org.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$1 {

    static final FunctionDescriptor fuse_opt_insert_arg$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fuse_opt_insert_arg$MH = RuntimeHelper.downcallHandle(
        "fuse_opt_insert_arg",
        constants$1.fuse_opt_insert_arg$FUNC
    );
    static final FunctionDescriptor fuse_opt_free_args$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fuse_opt_free_args$MH = RuntimeHelper.downcallHandle(
        "fuse_opt_free_args",
        constants$1.fuse_opt_free_args$FUNC
    );
    static final FunctionDescriptor fuse_opt_match$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fuse_opt_match$MH = RuntimeHelper.downcallHandle(
        "fuse_opt_match",
        constants$1.fuse_opt_match$FUNC
    );
    static final FunctionDescriptor _OSSwapInt16$FUNC = FunctionDescriptor.of(Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT
    );
    static final MethodHandle _OSSwapInt16$MH = RuntimeHelper.downcallHandle(
        "_OSSwapInt16",
        constants$1._OSSwapInt16$FUNC
    );
    static final FunctionDescriptor _OSSwapInt32$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle _OSSwapInt32$MH = RuntimeHelper.downcallHandle(
        "_OSSwapInt32",
        constants$1._OSSwapInt32$FUNC
    );
    static final FunctionDescriptor _OSSwapInt64$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle _OSSwapInt64$MH = RuntimeHelper.downcallHandle(
        "_OSSwapInt64",
        constants$1._OSSwapInt64$FUNC
    );
}


