// Generated by jextract

package org.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$40 {

    static final MemoryAddress __DARWIN_NULL$ADDR = MemoryAddress.ofLong(0L);
    static final MemoryAddress _FILESEC_UNSET_PROPERTY$ADDR = MemoryAddress.ofLong(0L);
    static final MemoryAddress _FILESEC_REMOVE_ACL$ADDR = MemoryAddress.ofLong(1L);
    static final MemoryAddress NULL$ADDR = MemoryAddress.ofLong(0L);
    static final MemoryAddress SIG_DFL$ADDR = MemoryAddress.ofLong(0L);
    static final MemoryAddress SIG_IGN$ADDR = MemoryAddress.ofLong(1L);
}


