// Generated by jextract

package org.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$7 {

    static final FunctionDescriptor lchflags$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle lchflags$MH = RuntimeHelper.downcallHandle(
        "lchflags",
        constants$7.lchflags$FUNC
    );
    static final FunctionDescriptor lchmod$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_SHORT$LAYOUT
    );
    static final MethodHandle lchmod$MH = RuntimeHelper.downcallHandle(
        "lchmod",
        constants$7.lchmod$FUNC
    );
    static final FunctionDescriptor lstatx_np$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle lstatx_np$MH = RuntimeHelper.downcallHandle(
        "lstatx_np",
        constants$7.lstatx_np$FUNC
    );
    static final FunctionDescriptor mkdirx_np$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle mkdirx_np$MH = RuntimeHelper.downcallHandle(
        "mkdirx_np",
        constants$7.mkdirx_np$FUNC
    );
    static final FunctionDescriptor mkfifox_np$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle mkfifox_np$MH = RuntimeHelper.downcallHandle(
        "mkfifox_np",
        constants$7.mkfifox_np$FUNC
    );
    static final FunctionDescriptor statx_np$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle statx_np$MH = RuntimeHelper.downcallHandle(
        "statx_np",
        constants$7.statx_np$FUNC
    );
}


