// Generated by jextract

package org.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$24 {

    static final FunctionDescriptor getfsstat$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle getfsstat$MH = RuntimeHelper.downcallHandle(
        "getfsstat",
        constants$24.getfsstat$FUNC
    );
    static final FunctionDescriptor getmntinfo$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle getmntinfo$MH = RuntimeHelper.downcallHandle(
        "getmntinfo",
        constants$24.getmntinfo$FUNC
    );
    static final FunctionDescriptor getmntinfo_r_np$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle getmntinfo_r_np$MH = RuntimeHelper.downcallHandle(
        "getmntinfo_r_np",
        constants$24.getmntinfo_r_np$FUNC
    );
    static final FunctionDescriptor mount$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle mount$MH = RuntimeHelper.downcallHandle(
        "mount",
        constants$24.mount$FUNC
    );
    static final FunctionDescriptor fmount$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fmount$MH = RuntimeHelper.downcallHandle(
        "fmount",
        constants$24.fmount$FUNC
    );
    static final FunctionDescriptor statfs$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle statfs$MH = RuntimeHelper.downcallHandle(
        "statfs",
        constants$24.statfs$FUNC
    );
}


