// Generated by jextract

package org.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$6 {

    static final FunctionDescriptor utimensat$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle utimensat$MH = RuntimeHelper.downcallHandle(
        "utimensat",
        constants$6.utimensat$FUNC
    );
    static final FunctionDescriptor chflags$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle chflags$MH = RuntimeHelper.downcallHandle(
        "chflags",
        constants$6.chflags$FUNC
    );
    static final FunctionDescriptor chmodx_np$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle chmodx_np$MH = RuntimeHelper.downcallHandle(
        "chmodx_np",
        constants$6.chmodx_np$FUNC
    );
    static final FunctionDescriptor fchflags$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle fchflags$MH = RuntimeHelper.downcallHandle(
        "fchflags",
        constants$6.fchflags$FUNC
    );
    static final FunctionDescriptor fchmodx_np$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fchmodx_np$MH = RuntimeHelper.downcallHandle(
        "fchmodx_np",
        constants$6.fchmodx_np$FUNC
    );
    static final FunctionDescriptor fstatx_np$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fstatx_np$MH = RuntimeHelper.downcallHandle(
        "fstatx_np",
        constants$6.fstatx_np$FUNC
    );
}


