// Generated by jextract

package org.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$38 {

    static final FunctionDescriptor fuse_processor_t$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fuse_processor_t$MH = RuntimeHelper.downcallHandle(
        constants$38.fuse_processor_t$FUNC
    );
    static final FunctionDescriptor fuse_setup$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fuse_setup$MH = RuntimeHelper.downcallHandle(
        "fuse_setup",
        constants$38.fuse_setup$FUNC
    );
    static final FunctionDescriptor fuse_teardown$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fuse_teardown$MH = RuntimeHelper.downcallHandle(
        "fuse_teardown",
        constants$38.fuse_teardown$FUNC
    );
    static final FunctionDescriptor fuse_read_cmd$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fuse_read_cmd$MH = RuntimeHelper.downcallHandle(
        "fuse_read_cmd",
        constants$38.fuse_read_cmd$FUNC
    );
    static final FunctionDescriptor fuse_process_cmd$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fuse_process_cmd$MH = RuntimeHelper.downcallHandle(
        "fuse_process_cmd",
        constants$38.fuse_process_cmd$FUNC
    );
    static final FunctionDescriptor fuse_loop_mt_proc$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fuse_loop_mt_proc$MH = RuntimeHelper.downcallHandle(
        "fuse_loop_mt_proc",
        constants$38.fuse_loop_mt_proc$FUNC
    );
}


