// Generated by jextract

package org.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$30 {

    static final FunctionDescriptor fuse_fs_rmdir$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fuse_fs_rmdir$MH = RuntimeHelper.downcallHandle(
        "fuse_fs_rmdir",
        constants$30.fuse_fs_rmdir$FUNC
    );
    static final FunctionDescriptor fuse_fs_symlink$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fuse_fs_symlink$MH = RuntimeHelper.downcallHandle(
        "fuse_fs_symlink",
        constants$30.fuse_fs_symlink$FUNC
    );
    static final FunctionDescriptor fuse_fs_link$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fuse_fs_link$MH = RuntimeHelper.downcallHandle(
        "fuse_fs_link",
        constants$30.fuse_fs_link$FUNC
    );
    static final FunctionDescriptor fuse_fs_release$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fuse_fs_release$MH = RuntimeHelper.downcallHandle(
        "fuse_fs_release",
        constants$30.fuse_fs_release$FUNC
    );
    static final FunctionDescriptor fuse_fs_open$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fuse_fs_open$MH = RuntimeHelper.downcallHandle(
        "fuse_fs_open",
        constants$30.fuse_fs_open$FUNC
    );
    static final FunctionDescriptor fuse_fs_read$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fuse_fs_read$MH = RuntimeHelper.downcallHandle(
        "fuse_fs_read",
        constants$30.fuse_fs_read$FUNC
    );
}


