// Generated by jextract

package org.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$39 {

    static final FunctionDescriptor fuse_exited$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fuse_exited$MH = RuntimeHelper.downcallHandle(
        "fuse_exited",
        constants$39.fuse_exited$FUNC
    );
    static final FunctionDescriptor fuse_set_getcontext_func$func$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle fuse_set_getcontext_func$func$MH = RuntimeHelper.downcallHandle(
        constants$39.fuse_set_getcontext_func$func$FUNC
    );
    static final FunctionDescriptor fuse_set_getcontext_func$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fuse_set_getcontext_func$MH = RuntimeHelper.downcallHandle(
        "fuse_set_getcontext_func",
        constants$39.fuse_set_getcontext_func$FUNC
    );
    static final FunctionDescriptor fuse_get_session$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fuse_get_session$MH = RuntimeHelper.downcallHandle(
        "fuse_get_session",
        constants$39.fuse_get_session$FUNC
    );
    static final MemorySegment __DARWIN_SUF_EXTSN$SEGMENT = RuntimeHelper.CONSTANT_ALLOCATOR.allocateUtf8String("$DARWIN_EXTSN");
}


