// Generated by jextract

package org.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$32 {

    static final FunctionDescriptor fuse_fs_statfs_x$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fuse_fs_statfs_x$MH = RuntimeHelper.downcallHandle(
        "fuse_fs_statfs_x",
        constants$32.fuse_fs_statfs_x$FUNC
    );
    static final FunctionDescriptor fuse_fs_opendir$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fuse_fs_opendir$MH = RuntimeHelper.downcallHandle(
        "fuse_fs_opendir",
        constants$32.fuse_fs_opendir$FUNC
    );
    static final FunctionDescriptor fuse_fs_readdir$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fuse_fs_readdir$MH = RuntimeHelper.downcallHandle(
        "fuse_fs_readdir",
        constants$32.fuse_fs_readdir$FUNC
    );
    static final FunctionDescriptor fuse_fs_fsyncdir$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fuse_fs_fsyncdir$MH = RuntimeHelper.downcallHandle(
        "fuse_fs_fsyncdir",
        constants$32.fuse_fs_fsyncdir$FUNC
    );
    static final FunctionDescriptor fuse_fs_releasedir$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fuse_fs_releasedir$MH = RuntimeHelper.downcallHandle(
        "fuse_fs_releasedir",
        constants$32.fuse_fs_releasedir$FUNC
    );
    static final FunctionDescriptor fuse_fs_create$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle fuse_fs_create$MH = RuntimeHelper.downcallHandle(
        "fuse_fs_create",
        constants$32.fuse_fs_create$FUNC
    );
}


