// Generated by jextract

package org.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$2 {

    static final FunctionDescriptor OSReadSwapInt16$FUNC = FunctionDescriptor.of(Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle OSReadSwapInt16$MH = RuntimeHelper.downcallHandle(
        "OSReadSwapInt16",
        constants$2.OSReadSwapInt16$FUNC
    );
    static final FunctionDescriptor OSReadSwapInt32$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle OSReadSwapInt32$MH = RuntimeHelper.downcallHandle(
        "OSReadSwapInt32",
        constants$2.OSReadSwapInt32$FUNC
    );
    static final FunctionDescriptor OSReadSwapInt64$FUNC = FunctionDescriptor.of(Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle OSReadSwapInt64$MH = RuntimeHelper.downcallHandle(
        "OSReadSwapInt64",
        constants$2.OSReadSwapInt64$FUNC
    );
    static final FunctionDescriptor OSWriteSwapInt16$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_SHORT$LAYOUT
    );
    static final MethodHandle OSWriteSwapInt16$MH = RuntimeHelper.downcallHandle(
        "OSWriteSwapInt16",
        constants$2.OSWriteSwapInt16$FUNC
    );
    static final FunctionDescriptor OSWriteSwapInt32$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle OSWriteSwapInt32$MH = RuntimeHelper.downcallHandle(
        "OSWriteSwapInt32",
        constants$2.OSWriteSwapInt32$FUNC
    );
    static final FunctionDescriptor OSWriteSwapInt64$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT,
        Constants$root.C_LONG_LONG$LAYOUT
    );
    static final MethodHandle OSWriteSwapInt64$MH = RuntimeHelper.downcallHandle(
        "OSWriteSwapInt64",
        constants$2.OSWriteSwapInt64$FUNC
    );
}


