// Generated by jextract

package org.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$11 {

    static final FunctionDescriptor filesec_init$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT);
    static final MethodHandle filesec_init$MH = RuntimeHelper.downcallHandle(
        "filesec_init",
        constants$11.filesec_init$FUNC
    );
    static final FunctionDescriptor filesec_dup$FUNC = FunctionDescriptor.of(Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle filesec_dup$MH = RuntimeHelper.downcallHandle(
        "filesec_dup",
        constants$11.filesec_dup$FUNC
    );
    static final FunctionDescriptor filesec_free$FUNC = FunctionDescriptor.ofVoid(
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle filesec_free$MH = RuntimeHelper.downcallHandle(
        "filesec_free",
        constants$11.filesec_free$FUNC
    );
    static final FunctionDescriptor filesec_get_property$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle filesec_get_property$MH = RuntimeHelper.downcallHandle(
        "filesec_get_property",
        constants$11.filesec_get_property$FUNC
    );
    static final FunctionDescriptor filesec_query_property$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle filesec_query_property$MH = RuntimeHelper.downcallHandle(
        "filesec_query_property",
        constants$11.filesec_query_property$FUNC
    );
    static final FunctionDescriptor filesec_set_property$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle filesec_set_property$MH = RuntimeHelper.downcallHandle(
        "filesec_set_property",
        constants$11.filesec_set_property$FUNC
    );
}


