// Generated by jextract

package org.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
class constants$5 {

    static final FunctionDescriptor mknod$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle mknod$MH = RuntimeHelper.downcallHandle(
        "mknod",
        constants$5.mknod$FUNC
    );
    static final FunctionDescriptor umask$FUNC = FunctionDescriptor.of(Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_SHORT$LAYOUT
    );
    static final MethodHandle umask$MH = RuntimeHelper.downcallHandle(
        "umask",
        constants$5.umask$FUNC
    );
    static final FunctionDescriptor fchmodat$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_SHORT$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle fchmodat$MH = RuntimeHelper.downcallHandle(
        "fchmodat",
        constants$5.fchmodat$FUNC
    );
    static final FunctionDescriptor fstatat$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_INT$LAYOUT
    );
    static final MethodHandle fstatat$MH = RuntimeHelper.downcallHandle(
        "fstatat",
        constants$5.fstatat$FUNC
    );
    static final FunctionDescriptor mkdirat$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT,
        Constants$root.C_SHORT$LAYOUT
    );
    static final MethodHandle mkdirat$MH = RuntimeHelper.downcallHandle(
        "mkdirat",
        constants$5.mkdirat$FUNC
    );
    static final FunctionDescriptor futimens$FUNC = FunctionDescriptor.of(Constants$root.C_INT$LAYOUT,
        Constants$root.C_INT$LAYOUT,
        Constants$root.C_POINTER$LAYOUT
    );
    static final MethodHandle futimens$MH = RuntimeHelper.downcallHandle(
        "futimens",
        constants$5.futimens$FUNC
    );
}


