// Generated by jextract

package org.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class diskextent {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("startblock"),
        Constants$root.C_INT$LAYOUT.withName("blockcount")
    ).withName("diskextent");
    public static MemoryLayout $LAYOUT() {
        return diskextent.$struct$LAYOUT;
    }
    static final VarHandle startblock$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("startblock"));
    public static VarHandle startblock$VH() {
        return diskextent.startblock$VH;
    }
    public static int startblock$get(MemorySegment seg) {
        return (int)diskextent.startblock$VH.get(seg);
    }
    public static void startblock$set( MemorySegment seg, int x) {
        diskextent.startblock$VH.set(seg, x);
    }
    public static int startblock$get(MemorySegment seg, long index) {
        return (int)diskextent.startblock$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void startblock$set(MemorySegment seg, long index, int x) {
        diskextent.startblock$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle blockcount$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("blockcount"));
    public static VarHandle blockcount$VH() {
        return diskextent.blockcount$VH;
    }
    public static int blockcount$get(MemorySegment seg) {
        return (int)diskextent.blockcount$VH.get(seg);
    }
    public static void blockcount$set( MemorySegment seg, int x) {
        diskextent.blockcount$VH.set(seg, x);
    }
    public static int blockcount$get(MemorySegment seg, long index) {
        return (int)diskextent.blockcount$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void blockcount$set(MemorySegment seg, long index, int x) {
        diskextent.blockcount$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


