// Generated by jextract

package org.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class fhandle {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("fh_len"),
        MemoryLayout.sequenceLayout(128, Constants$root.C_CHAR$LAYOUT).withName("fh_data")
    ).withName("fhandle");
    public static MemoryLayout $LAYOUT() {
        return fhandle.$struct$LAYOUT;
    }
    static final VarHandle fh_len$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("fh_len"));
    public static VarHandle fh_len$VH() {
        return fhandle.fh_len$VH;
    }
    public static int fh_len$get(MemorySegment seg) {
        return (int)fhandle.fh_len$VH.get(seg);
    }
    public static void fh_len$set( MemorySegment seg, int x) {
        fhandle.fh_len$VH.set(seg, x);
    }
    public static int fh_len$get(MemorySegment seg, long index) {
        return (int)fhandle.fh_len$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void fh_len$set(MemorySegment seg, long index, int x) {
        fhandle.fh_len$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment fh_data$slice(MemorySegment seg) {
        return seg.asSlice(4, 128);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


