// Generated by jextract

package org.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class fsignatures {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG_LONG$LAYOUT.withName("fs_file_start"),
        Constants$root.C_POINTER$LAYOUT.withName("fs_blob_start"),
        Constants$root.C_LONG_LONG$LAYOUT.withName("fs_blob_size"),
        Constants$root.C_LONG_LONG$LAYOUT.withName("fs_fsignatures_size"),
        MemoryLayout.sequenceLayout(20, Constants$root.C_CHAR$LAYOUT).withName("fs_cdhash"),
        Constants$root.C_INT$LAYOUT.withName("fs_hash_type")
    ).withName("fsignatures");
    public static MemoryLayout $LAYOUT() {
        return fsignatures.$struct$LAYOUT;
    }
    static final VarHandle fs_file_start$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("fs_file_start"));
    public static VarHandle fs_file_start$VH() {
        return fsignatures.fs_file_start$VH;
    }
    public static long fs_file_start$get(MemorySegment seg) {
        return (long)fsignatures.fs_file_start$VH.get(seg);
    }
    public static void fs_file_start$set( MemorySegment seg, long x) {
        fsignatures.fs_file_start$VH.set(seg, x);
    }
    public static long fs_file_start$get(MemorySegment seg, long index) {
        return (long)fsignatures.fs_file_start$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void fs_file_start$set(MemorySegment seg, long index, long x) {
        fsignatures.fs_file_start$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle fs_blob_start$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("fs_blob_start"));
    public static VarHandle fs_blob_start$VH() {
        return fsignatures.fs_blob_start$VH;
    }
    public static MemoryAddress fs_blob_start$get(MemorySegment seg) {
        return (java.lang.foreign.MemoryAddress)fsignatures.fs_blob_start$VH.get(seg);
    }
    public static void fs_blob_start$set( MemorySegment seg, MemoryAddress x) {
        fsignatures.fs_blob_start$VH.set(seg, x);
    }
    public static MemoryAddress fs_blob_start$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemoryAddress)fsignatures.fs_blob_start$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void fs_blob_start$set(MemorySegment seg, long index, MemoryAddress x) {
        fsignatures.fs_blob_start$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle fs_blob_size$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("fs_blob_size"));
    public static VarHandle fs_blob_size$VH() {
        return fsignatures.fs_blob_size$VH;
    }
    public static long fs_blob_size$get(MemorySegment seg) {
        return (long)fsignatures.fs_blob_size$VH.get(seg);
    }
    public static void fs_blob_size$set( MemorySegment seg, long x) {
        fsignatures.fs_blob_size$VH.set(seg, x);
    }
    public static long fs_blob_size$get(MemorySegment seg, long index) {
        return (long)fsignatures.fs_blob_size$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void fs_blob_size$set(MemorySegment seg, long index, long x) {
        fsignatures.fs_blob_size$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle fs_fsignatures_size$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("fs_fsignatures_size"));
    public static VarHandle fs_fsignatures_size$VH() {
        return fsignatures.fs_fsignatures_size$VH;
    }
    public static long fs_fsignatures_size$get(MemorySegment seg) {
        return (long)fsignatures.fs_fsignatures_size$VH.get(seg);
    }
    public static void fs_fsignatures_size$set( MemorySegment seg, long x) {
        fsignatures.fs_fsignatures_size$VH.set(seg, x);
    }
    public static long fs_fsignatures_size$get(MemorySegment seg, long index) {
        return (long)fsignatures.fs_fsignatures_size$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void fs_fsignatures_size$set(MemorySegment seg, long index, long x) {
        fsignatures.fs_fsignatures_size$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment fs_cdhash$slice(MemorySegment seg) {
        return seg.asSlice(32, 20);
    }
    static final VarHandle fs_hash_type$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("fs_hash_type"));
    public static VarHandle fs_hash_type$VH() {
        return fsignatures.fs_hash_type$VH;
    }
    public static int fs_hash_type$get(MemorySegment seg) {
        return (int)fsignatures.fs_hash_type$VH.get(seg);
    }
    public static void fs_hash_type$set( MemorySegment seg, int x) {
        fsignatures.fs_hash_type$VH.set(seg, x);
    }
    public static int fs_hash_type$get(MemorySegment seg, long index) {
        return (int)fsignatures.fs_hash_type$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void fs_hash_type$set(MemorySegment seg, long index, int x) {
        fsignatures.fs_hash_type$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


