// Generated by jextract

package org.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class fsobj_id {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("fid_objno"),
        Constants$root.C_INT$LAYOUT.withName("fid_generation")
    ).withName("fsobj_id");
    public static MemoryLayout $LAYOUT() {
        return fsobj_id.$struct$LAYOUT;
    }
    static final VarHandle fid_objno$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("fid_objno"));
    public static VarHandle fid_objno$VH() {
        return fsobj_id.fid_objno$VH;
    }
    public static int fid_objno$get(MemorySegment seg) {
        return (int)fsobj_id.fid_objno$VH.get(seg);
    }
    public static void fid_objno$set( MemorySegment seg, int x) {
        fsobj_id.fid_objno$VH.set(seg, x);
    }
    public static int fid_objno$get(MemorySegment seg, long index) {
        return (int)fsobj_id.fid_objno$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void fid_objno$set(MemorySegment seg, long index, int x) {
        fsobj_id.fid_objno$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle fid_generation$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("fid_generation"));
    public static VarHandle fid_generation$VH() {
        return fsobj_id.fid_generation$VH;
    }
    public static int fid_generation$get(MemorySegment seg) {
        return (int)fsobj_id.fid_generation$VH.get(seg);
    }
    public static void fid_generation$set( MemorySegment seg, int x) {
        fsobj_id.fid_generation$VH.set(seg, x);
    }
    public static int fid_generation$get(MemorySegment seg, long index) {
        return (int)fsobj_id.fid_generation$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void fid_generation$set(MemorySegment seg, long index, int x) {
        fsobj_id.fid_generation$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


