// Generated by jextract

package org.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class fsupplement {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG_LONG$LAYOUT.withName("fs_file_start"),
        Constants$root.C_LONG_LONG$LAYOUT.withName("fs_blob_start"),
        Constants$root.C_LONG_LONG$LAYOUT.withName("fs_blob_size"),
        Constants$root.C_INT$LAYOUT.withName("fs_orig_fd"),
        MemoryLayout.paddingLayout(32)
    ).withName("fsupplement");
    public static MemoryLayout $LAYOUT() {
        return fsupplement.$struct$LAYOUT;
    }
    static final VarHandle fs_file_start$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("fs_file_start"));
    public static VarHandle fs_file_start$VH() {
        return fsupplement.fs_file_start$VH;
    }
    public static long fs_file_start$get(MemorySegment seg) {
        return (long)fsupplement.fs_file_start$VH.get(seg);
    }
    public static void fs_file_start$set( MemorySegment seg, long x) {
        fsupplement.fs_file_start$VH.set(seg, x);
    }
    public static long fs_file_start$get(MemorySegment seg, long index) {
        return (long)fsupplement.fs_file_start$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void fs_file_start$set(MemorySegment seg, long index, long x) {
        fsupplement.fs_file_start$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle fs_blob_start$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("fs_blob_start"));
    public static VarHandle fs_blob_start$VH() {
        return fsupplement.fs_blob_start$VH;
    }
    public static long fs_blob_start$get(MemorySegment seg) {
        return (long)fsupplement.fs_blob_start$VH.get(seg);
    }
    public static void fs_blob_start$set( MemorySegment seg, long x) {
        fsupplement.fs_blob_start$VH.set(seg, x);
    }
    public static long fs_blob_start$get(MemorySegment seg, long index) {
        return (long)fsupplement.fs_blob_start$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void fs_blob_start$set(MemorySegment seg, long index, long x) {
        fsupplement.fs_blob_start$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle fs_blob_size$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("fs_blob_size"));
    public static VarHandle fs_blob_size$VH() {
        return fsupplement.fs_blob_size$VH;
    }
    public static long fs_blob_size$get(MemorySegment seg) {
        return (long)fsupplement.fs_blob_size$VH.get(seg);
    }
    public static void fs_blob_size$set( MemorySegment seg, long x) {
        fsupplement.fs_blob_size$VH.set(seg, x);
    }
    public static long fs_blob_size$get(MemorySegment seg, long index) {
        return (long)fsupplement.fs_blob_size$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void fs_blob_size$set(MemorySegment seg, long index, long x) {
        fsupplement.fs_blob_size$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle fs_orig_fd$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("fs_orig_fd"));
    public static VarHandle fs_orig_fd$VH() {
        return fsupplement.fs_orig_fd$VH;
    }
    public static int fs_orig_fd$get(MemorySegment seg) {
        return (int)fsupplement.fs_orig_fd$VH.get(seg);
    }
    public static void fs_orig_fd$set( MemorySegment seg, int x) {
        fsupplement.fs_orig_fd$VH.set(seg, x);
    }
    public static int fs_orig_fd$get(MemorySegment seg, long index) {
        return (int)fsupplement.fs_orig_fd$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void fs_orig_fd$set(MemorySegment seg, long index, int x) {
        fsupplement.fs_orig_fd$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


