// Generated by jextract

package org.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class ftrimactivefile {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_LONG_LONG$LAYOUT.withName("fta_offset"),
        Constants$root.C_LONG_LONG$LAYOUT.withName("fta_length")
    ).withName("ftrimactivefile");
    public static MemoryLayout $LAYOUT() {
        return ftrimactivefile.$struct$LAYOUT;
    }
    static final VarHandle fta_offset$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("fta_offset"));
    public static VarHandle fta_offset$VH() {
        return ftrimactivefile.fta_offset$VH;
    }
    public static long fta_offset$get(MemorySegment seg) {
        return (long)ftrimactivefile.fta_offset$VH.get(seg);
    }
    public static void fta_offset$set( MemorySegment seg, long x) {
        ftrimactivefile.fta_offset$VH.set(seg, x);
    }
    public static long fta_offset$get(MemorySegment seg, long index) {
        return (long)ftrimactivefile.fta_offset$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void fta_offset$set(MemorySegment seg, long index, long x) {
        ftrimactivefile.fta_offset$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle fta_length$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("fta_length"));
    public static VarHandle fta_length$VH() {
        return ftrimactivefile.fta_length$VH;
    }
    public static long fta_length$get(MemorySegment seg) {
        return (long)ftrimactivefile.fta_length$VH.get(seg);
    }
    public static void fta_length$set( MemorySegment seg, long x) {
        ftrimactivefile.fta_length$VH.set(seg, x);
    }
    public static long fta_length$get(MemorySegment seg, long index) {
        return (long)ftrimactivefile.fta_length$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void fta_length$set(MemorySegment seg, long index, long x) {
        ftrimactivefile.fta_length$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


