// Generated by jextract

package org.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public interface fuse_set_getcontext_func$func {

    java.lang.foreign.Addressable apply();
    static MemorySegment allocate(fuse_set_getcontext_func$func fi, MemorySession session) {
        return RuntimeHelper.upcallStub(fuse_set_getcontext_func$func.class, fi, constants$39.fuse_set_getcontext_func$func$FUNC, session);
    }
    static fuse_set_getcontext_func$func ofAddress(MemoryAddress addr, MemorySession session) {
        MemorySegment symbol = MemorySegment.ofAddress(addr, 0, session);
        return () -> {
            try {
                return (java.lang.foreign.Addressable)(java.lang.foreign.MemoryAddress)constants$39.fuse_set_getcontext_func$func$MH.invokeExact((Addressable)symbol);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


