// Generated by jextract

package org.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class fuse_opt {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_POINTER$LAYOUT.withName("templ"),
        Constants$root.C_LONG_LONG$LAYOUT.withName("offset"),
        Constants$root.C_INT$LAYOUT.withName("value"),
        MemoryLayout.paddingLayout(32)
    ).withName("fuse_opt");
    public static MemoryLayout $LAYOUT() {
        return fuse_opt.$struct$LAYOUT;
    }
    static final VarHandle templ$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("templ"));
    public static VarHandle templ$VH() {
        return fuse_opt.templ$VH;
    }
    public static MemoryAddress templ$get(MemorySegment seg) {
        return (java.lang.foreign.MemoryAddress)fuse_opt.templ$VH.get(seg);
    }
    public static void templ$set( MemorySegment seg, MemoryAddress x) {
        fuse_opt.templ$VH.set(seg, x);
    }
    public static MemoryAddress templ$get(MemorySegment seg, long index) {
        return (java.lang.foreign.MemoryAddress)fuse_opt.templ$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void templ$set(MemorySegment seg, long index, MemoryAddress x) {
        fuse_opt.templ$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle offset$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("offset"));
    public static VarHandle offset$VH() {
        return fuse_opt.offset$VH;
    }
    public static long offset$get(MemorySegment seg) {
        return (long)fuse_opt.offset$VH.get(seg);
    }
    public static void offset$set( MemorySegment seg, long x) {
        fuse_opt.offset$VH.set(seg, x);
    }
    public static long offset$get(MemorySegment seg, long index) {
        return (long)fuse_opt.offset$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void offset$set(MemorySegment seg, long index, long x) {
        fuse_opt.offset$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle value$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("value"));
    public static VarHandle value$VH() {
        return fuse_opt.value$VH;
    }
    public static int value$get(MemorySegment seg) {
        return (int)fuse_opt.value$VH.get(seg);
    }
    public static void value$set( MemorySegment seg, int x) {
        fuse_opt.value$VH.set(seg, x);
    }
    public static int value$get(MemorySegment seg, long index) {
        return (int)fuse_opt.value$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void value$set(MemorySegment seg, long index, int x) {
        fuse_opt.value$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


