// Generated by jextract

package org.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class fuse_h extends fuse_h_1 {

    /* package-private */ fuse_h() {}
    public static OfByte C_CHAR = Constants$root.C_CHAR$LAYOUT;
    public static OfShort C_SHORT = Constants$root.C_SHORT$LAYOUT;
    public static OfInt C_INT = Constants$root.C_INT$LAYOUT;
    public static OfLong C_LONG = Constants$root.C_LONG_LONG$LAYOUT;
    public static OfLong C_LONG_LONG = Constants$root.C_LONG_LONG$LAYOUT;
    public static OfFloat C_FLOAT = Constants$root.C_FLOAT$LAYOUT;
    public static OfDouble C_DOUBLE = Constants$root.C_DOUBLE$LAYOUT;
    public static OfAddress C_POINTER = Constants$root.C_POINTER$LAYOUT;
    public static int __WORDSIZE() {
        return (int)64L;
    }
    public static int __DARWIN_ONLY_64_BIT_INO_T() {
        return (int)1L;
    }
    public static int __DARWIN_ONLY_UNIX_CONFORMANCE() {
        return (int)1L;
    }
    public static int __DARWIN_ONLY_VERS_1050() {
        return (int)1L;
    }
    public static int __DARWIN_UNIX03() {
        return (int)1L;
    }
    public static int __DARWIN_64_BIT_INO_T() {
        return (int)1L;
    }
    public static int __DARWIN_VERS_1050() {
        return (int)1L;
    }
    public static int __DARWIN_NON_CANCELABLE() {
        return (int)0L;
    }
    public static int __STDC_WANT_LIB_EXT1__() {
        return (int)1L;
    }
    public static int __DARWIN_NO_LONG_LONG() {
        return (int)0L;
    }
    public static int _DARWIN_FEATURE_64_BIT_INODE() {
        return (int)1L;
    }
    public static int _DARWIN_FEATURE_ONLY_64_BIT_INODE() {
        return (int)1L;
    }
    public static int _DARWIN_FEATURE_ONLY_VERS_1050() {
        return (int)1L;
    }
    public static int _DARWIN_FEATURE_ONLY_UNIX_CONFORMANCE() {
        return (int)1L;
    }
    public static int _DARWIN_FEATURE_UNIX_CONFORMANCE() {
        return (int)3L;
    }
    public static int __has_ptrcheck() {
        return (int)0L;
    }
    public static int __PTHREAD_SIZE__() {
        return (int)8176L;
    }
    public static int __PTHREAD_ATTR_SIZE__() {
        return (int)56L;
    }
    public static int __PTHREAD_MUTEXATTR_SIZE__() {
        return (int)8L;
    }
    public static int __PTHREAD_MUTEX_SIZE__() {
        return (int)56L;
    }
    public static int __PTHREAD_CONDATTR_SIZE__() {
        return (int)8L;
    }
    public static int __PTHREAD_COND_SIZE__() {
        return (int)40L;
    }
    public static int __PTHREAD_ONCE_SIZE__() {
        return (int)8L;
    }
    public static int __PTHREAD_RWLOCK_SIZE__() {
        return (int)192L;
    }
    public static int __PTHREAD_RWLOCKATTR_SIZE__() {
        return (int)16L;
    }
    public static int INT8_MAX() {
        return (int)127L;
    }
    public static int INT16_MAX() {
        return (int)32767L;
    }
    public static int INT32_MAX() {
        return (int)2147483647L;
    }
    public static int UINT8_MAX() {
        return (int)255L;
    }
    public static int UINT16_MAX() {
        return (int)65535L;
    }
    public static int _QUAD_HIGHWORD() {
        return (int)1L;
    }
    public static int _QUAD_LOWWORD() {
        return (int)0L;
    }
    public static int __DARWIN_LITTLE_ENDIAN() {
        return (int)1234L;
    }
    public static int __DARWIN_BIG_ENDIAN() {
        return (int)4321L;
    }
    public static int __DARWIN_PDP_ENDIAN() {
        return (int)3412L;
    }
    public static int __API_TO_BE_DEPRECATED() {
        return (int)100000L;
    }
    public static int __MAC_10_0() {
        return (int)1000L;
    }
    public static int __MAC_10_1() {
        return (int)1010L;
    }
    public static int __MAC_10_2() {
        return (int)1020L;
    }
    public static int __MAC_10_3() {
        return (int)1030L;
    }
    public static int __MAC_10_4() {
        return (int)1040L;
    }
    public static int __MAC_10_5() {
        return (int)1050L;
    }
    public static int __MAC_10_6() {
        return (int)1060L;
    }
    public static int __MAC_10_7() {
        return (int)1070L;
    }
    public static int __MAC_10_8() {
        return (int)1080L;
    }
    public static int __MAC_10_9() {
        return (int)1090L;
    }
    public static int __MAC_10_10() {
        return (int)101000L;
    }
    public static int __MAC_10_10_2() {
        return (int)101002L;
    }
    public static int __MAC_10_10_3() {
        return (int)101003L;
    }
    public static int __MAC_10_11() {
        return (int)101100L;
    }
    public static int __MAC_10_11_2() {
        return (int)101102L;
    }
    public static int __MAC_10_11_3() {
        return (int)101103L;
    }
    public static int __MAC_10_11_4() {
        return (int)101104L;
    }
    public static int __MAC_10_12() {
        return (int)101200L;
    }
    public static int __MAC_10_12_1() {
        return (int)101201L;
    }
    public static int __MAC_10_12_2() {
        return (int)101202L;
    }
    public static int __MAC_10_12_4() {
        return (int)101204L;
    }
    public static int __MAC_10_13() {
        return (int)101300L;
    }
    public static int __MAC_10_13_1() {
        return (int)101301L;
    }
    public static int __MAC_10_13_2() {
        return (int)101302L;
    }
    public static int __MAC_10_13_4() {
        return (int)101304L;
    }
    public static int __MAC_10_14() {
        return (int)101400L;
    }
    public static int __MAC_10_14_1() {
        return (int)101401L;
    }
    public static int __MAC_10_14_4() {
        return (int)101404L;
    }
    public static int __MAC_10_14_6() {
        return (int)101406L;
    }
    public static int __MAC_10_15() {
        return (int)101500L;
    }
    public static int __MAC_10_15_1() {
        return (int)101501L;
    }
    public static int __MAC_10_15_4() {
        return (int)101504L;
    }
    public static int __MAC_10_16() {
        return (int)101600L;
    }
    public static int __MAC_11_0() {
        return (int)110000L;
    }
    public static int __MAC_11_1() {
        return (int)110100L;
    }
    public static int __MAC_11_3() {
        return (int)110300L;
    }
    public static int __MAC_11_4() {
        return (int)110400L;
    }
    public static int __MAC_11_5() {
        return (int)110500L;
    }
    public static int __MAC_11_6() {
        return (int)110600L;
    }
    public static int __MAC_12_0() {
        return (int)120000L;
    }
    public static int __MAC_12_1() {
        return (int)120100L;
    }
    public static int __MAC_12_2() {
        return (int)120200L;
    }
    public static int __MAC_12_3() {
        return (int)120300L;
    }
    public static int __IPHONE_2_0() {
        return (int)20000L;
    }
    public static int __IPHONE_2_1() {
        return (int)20100L;
    }
    public static int __IPHONE_2_2() {
        return (int)20200L;
    }
    public static int __IPHONE_3_0() {
        return (int)30000L;
    }
    public static int __IPHONE_3_1() {
        return (int)30100L;
    }
    public static int __IPHONE_3_2() {
        return (int)30200L;
    }
    public static int __IPHONE_4_0() {
        return (int)40000L;
    }
    public static int __IPHONE_4_1() {
        return (int)40100L;
    }
    public static int __IPHONE_4_2() {
        return (int)40200L;
    }
    public static int __IPHONE_4_3() {
        return (int)40300L;
    }
    public static int __IPHONE_5_0() {
        return (int)50000L;
    }
    public static int __IPHONE_5_1() {
        return (int)50100L;
    }
    public static int __IPHONE_6_0() {
        return (int)60000L;
    }
    public static int __IPHONE_6_1() {
        return (int)60100L;
    }
    public static int __IPHONE_7_0() {
        return (int)70000L;
    }
    public static int __IPHONE_7_1() {
        return (int)70100L;
    }
    public static int __IPHONE_8_0() {
        return (int)80000L;
    }
    public static int __IPHONE_8_1() {
        return (int)80100L;
    }
    public static int __IPHONE_8_2() {
        return (int)80200L;
    }
    public static int __IPHONE_8_3() {
        return (int)80300L;
    }
    public static int __IPHONE_8_4() {
        return (int)80400L;
    }
    public static int __IPHONE_9_0() {
        return (int)90000L;
    }
    public static int __IPHONE_9_1() {
        return (int)90100L;
    }
    public static int __IPHONE_9_2() {
        return (int)90200L;
    }
    public static int __IPHONE_9_3() {
        return (int)90300L;
    }
    public static int __IPHONE_10_0() {
        return (int)100000L;
    }
    public static int __IPHONE_10_1() {
        return (int)100100L;
    }
    public static int __IPHONE_10_2() {
        return (int)100200L;
    }
    public static int __IPHONE_10_3() {
        return (int)100300L;
    }
    public static int __IPHONE_11_0() {
        return (int)110000L;
    }
    public static int __IPHONE_11_1() {
        return (int)110100L;
    }
    public static int __IPHONE_11_2() {
        return (int)110200L;
    }
    public static int __IPHONE_11_3() {
        return (int)110300L;
    }
    public static int __IPHONE_11_4() {
        return (int)110400L;
    }
    public static int __IPHONE_12_0() {
        return (int)120000L;
    }
    public static int __IPHONE_12_1() {
        return (int)120100L;
    }
    public static int __IPHONE_12_2() {
        return (int)120200L;
    }
    public static int __IPHONE_12_3() {
        return (int)120300L;
    }
    public static int __IPHONE_12_4() {
        return (int)120400L;
    }
    public static int __IPHONE_13_0() {
        return (int)130000L;
    }
    public static int __IPHONE_13_1() {
        return (int)130100L;
    }
    public static int __IPHONE_13_2() {
        return (int)130200L;
    }
    public static int __IPHONE_13_3() {
        return (int)130300L;
    }
    public static int __IPHONE_13_4() {
        return (int)130400L;
    }
    public static int __IPHONE_13_5() {
        return (int)130500L;
    }
    public static int __IPHONE_13_6() {
        return (int)130600L;
    }
    public static int __IPHONE_13_7() {
        return (int)130700L;
    }
    public static int __IPHONE_14_0() {
        return (int)140000L;
    }
    public static int __IPHONE_14_1() {
        return (int)140100L;
    }
    public static int __IPHONE_14_2() {
        return (int)140200L;
    }
    public static int __IPHONE_14_3() {
        return (int)140300L;
    }
    public static int __IPHONE_14_5() {
        return (int)140500L;
    }
    public static int __IPHONE_14_6() {
        return (int)140600L;
    }
    public static int __IPHONE_14_7() {
        return (int)140700L;
    }
    public static int __IPHONE_14_8() {
        return (int)140800L;
    }
    public static int __IPHONE_15_0() {
        return (int)150000L;
    }
    public static int __IPHONE_15_1() {
        return (int)150100L;
    }
    public static int __IPHONE_15_2() {
        return (int)150200L;
    }
    public static int __IPHONE_15_3() {
        return (int)150300L;
    }
    public static int __IPHONE_15_4() {
        return (int)150400L;
    }
    public static int __TVOS_9_0() {
        return (int)90000L;
    }
    public static int __TVOS_9_1() {
        return (int)90100L;
    }
    public static int __TVOS_9_2() {
        return (int)90200L;
    }
    public static int __TVOS_10_0() {
        return (int)100000L;
    }
    public static int __TVOS_10_0_1() {
        return (int)100001L;
    }
    public static int __TVOS_10_1() {
        return (int)100100L;
    }
    public static int __TVOS_10_2() {
        return (int)100200L;
    }
    public static int __TVOS_11_0() {
        return (int)110000L;
    }
    public static int __TVOS_11_1() {
        return (int)110100L;
    }
    public static int __TVOS_11_2() {
        return (int)110200L;
    }
    public static int __TVOS_11_3() {
        return (int)110300L;
    }
    public static int __TVOS_11_4() {
        return (int)110400L;
    }
    public static int __TVOS_12_0() {
        return (int)120000L;
    }
    public static int __TVOS_12_1() {
        return (int)120100L;
    }
    public static int __TVOS_12_2() {
        return (int)120200L;
    }
    public static int __TVOS_12_3() {
        return (int)120300L;
    }
    public static int __TVOS_12_4() {
        return (int)120400L;
    }
    public static int __TVOS_13_0() {
        return (int)130000L;
    }
    public static int __TVOS_13_2() {
        return (int)130200L;
    }
    public static int __TVOS_13_3() {
        return (int)130300L;
    }
    public static int __TVOS_13_4() {
        return (int)130400L;
    }
    public static int __TVOS_14_0() {
        return (int)140000L;
    }
    public static int __TVOS_14_1() {
        return (int)140100L;
    }
    public static int __TVOS_14_2() {
        return (int)140200L;
    }
    public static int __TVOS_14_3() {
        return (int)140300L;
    }
    public static int __TVOS_14_5() {
        return (int)140500L;
    }
    public static int __TVOS_14_6() {
        return (int)140600L;
    }
    public static int __TVOS_14_7() {
        return (int)140700L;
    }
    public static int __TVOS_15_0() {
        return (int)150000L;
    }
    public static int __TVOS_15_1() {
        return (int)150100L;
    }
    public static int __TVOS_15_2() {
        return (int)150200L;
    }
    public static int __TVOS_15_3() {
        return (int)150300L;
    }
    public static int __TVOS_15_4() {
        return (int)150400L;
    }
    public static int __WATCHOS_1_0() {
        return (int)10000L;
    }
    public static int __WATCHOS_2_0() {
        return (int)20000L;
    }
    public static int __WATCHOS_2_1() {
        return (int)20100L;
    }
    public static int __WATCHOS_2_2() {
        return (int)20200L;
    }
    public static int __WATCHOS_3_0() {
        return (int)30000L;
    }
    public static int __WATCHOS_3_1() {
        return (int)30100L;
    }
    public static int __WATCHOS_3_1_1() {
        return (int)30101L;
    }
    public static int __WATCHOS_3_2() {
        return (int)30200L;
    }
    public static int __WATCHOS_4_0() {
        return (int)40000L;
    }
    public static int __WATCHOS_4_1() {
        return (int)40100L;
    }
    public static int __WATCHOS_4_2() {
        return (int)40200L;
    }
    public static int __WATCHOS_4_3() {
        return (int)40300L;
    }
    public static int __WATCHOS_5_0() {
        return (int)50000L;
    }
    public static int __WATCHOS_5_1() {
        return (int)50100L;
    }
    public static int __WATCHOS_5_2() {
        return (int)50200L;
    }
    public static int __WATCHOS_5_3() {
        return (int)50300L;
    }
    public static int __WATCHOS_6_0() {
        return (int)60000L;
    }
    public static int __WATCHOS_6_1() {
        return (int)60100L;
    }
    public static int __WATCHOS_6_2() {
        return (int)60200L;
    }
    public static int __WATCHOS_7_0() {
        return (int)70000L;
    }
    public static int __WATCHOS_7_1() {
        return (int)70100L;
    }
    public static int __WATCHOS_7_2() {
        return (int)70200L;
    }
    public static int __WATCHOS_7_3() {
        return (int)70300L;
    }
    public static int __WATCHOS_7_4() {
        return (int)70400L;
    }
    public static int __WATCHOS_7_5() {
        return (int)70500L;
    }
    public static int __WATCHOS_7_6() {
        return (int)70600L;
    }
    public static int __WATCHOS_8_0() {
        return (int)80000L;
    }
    public static int __WATCHOS_8_1() {
        return (int)80100L;
    }
    public static int __WATCHOS_8_3() {
        return (int)80300L;
    }
    public static int __WATCHOS_8_4() {
        return (int)80400L;
    }
    public static int __WATCHOS_8_5() {
        return (int)80500L;
    }
    public static int MAC_OS_X_VERSION_10_0() {
        return (int)1000L;
    }
    public static int MAC_OS_X_VERSION_10_1() {
        return (int)1010L;
    }
    public static int MAC_OS_X_VERSION_10_2() {
        return (int)1020L;
    }
    public static int MAC_OS_X_VERSION_10_3() {
        return (int)1030L;
    }
    public static int MAC_OS_X_VERSION_10_4() {
        return (int)1040L;
    }
    public static int MAC_OS_X_VERSION_10_5() {
        return (int)1050L;
    }
    public static int MAC_OS_X_VERSION_10_6() {
        return (int)1060L;
    }
    public static int MAC_OS_X_VERSION_10_7() {
        return (int)1070L;
    }
    public static int MAC_OS_X_VERSION_10_8() {
        return (int)1080L;
    }
    public static int MAC_OS_X_VERSION_10_9() {
        return (int)1090L;
    }
    public static int MAC_OS_X_VERSION_10_10() {
        return (int)101000L;
    }
    public static int MAC_OS_X_VERSION_10_10_2() {
        return (int)101002L;
    }
    public static int MAC_OS_X_VERSION_10_10_3() {
        return (int)101003L;
    }
    public static int MAC_OS_X_VERSION_10_11() {
        return (int)101100L;
    }
    public static int MAC_OS_X_VERSION_10_11_2() {
        return (int)101102L;
    }
    public static int MAC_OS_X_VERSION_10_11_3() {
        return (int)101103L;
    }
    public static int MAC_OS_X_VERSION_10_11_4() {
        return (int)101104L;
    }
    public static int MAC_OS_X_VERSION_10_12() {
        return (int)101200L;
    }
    public static int MAC_OS_X_VERSION_10_12_1() {
        return (int)101201L;
    }
    public static int MAC_OS_X_VERSION_10_12_2() {
        return (int)101202L;
    }
    public static int MAC_OS_X_VERSION_10_12_4() {
        return (int)101204L;
    }
    public static int MAC_OS_X_VERSION_10_13() {
        return (int)101300L;
    }
    public static int MAC_OS_X_VERSION_10_13_1() {
        return (int)101301L;
    }
    public static int MAC_OS_X_VERSION_10_13_2() {
        return (int)101302L;
    }
    public static int MAC_OS_X_VERSION_10_13_4() {
        return (int)101304L;
    }
    public static int MAC_OS_X_VERSION_10_14() {
        return (int)101400L;
    }
    public static int MAC_OS_X_VERSION_10_14_1() {
        return (int)101401L;
    }
    public static int MAC_OS_X_VERSION_10_14_4() {
        return (int)101404L;
    }
    public static int MAC_OS_X_VERSION_10_14_6() {
        return (int)101406L;
    }
    public static int MAC_OS_X_VERSION_10_15() {
        return (int)101500L;
    }
    public static int MAC_OS_X_VERSION_10_15_1() {
        return (int)101501L;
    }
    public static int MAC_OS_X_VERSION_10_16() {
        return (int)101600L;
    }
    public static int MAC_OS_VERSION_11_0() {
        return (int)110000L;
    }
    public static int MAC_OS_VERSION_12_0() {
        return (int)120000L;
    }
    public static int __DRIVERKIT_19_0() {
        return (int)190000L;
    }
    public static int __DRIVERKIT_20_0() {
        return (int)200000L;
    }
    public static int __DRIVERKIT_21_0() {
        return (int)210000L;
    }
    public static int __ENABLE_LEGACY_MAC_AVAILABILITY() {
        return (int)1L;
    }
    public static int __DARWIN_FD_SETSIZE() {
        return (int)1024L;
    }
    public static int __DARWIN_NBBY() {
        return (int)8L;
    }
    public static int FUSE_MAJOR_VERSION() {
        return (int)2L;
    }
    public static int FUSE_MINOR_VERSION() {
        return (int)9L;
    }
    public static int S_IFMT() {
        return (int)61440L;
    }
    public static int S_IFIFO() {
        return (int)4096L;
    }
    public static int S_IFCHR() {
        return (int)8192L;
    }
    public static int S_IFDIR() {
        return (int)16384L;
    }
    public static int S_IFBLK() {
        return (int)24576L;
    }
    public static int S_IFREG() {
        return (int)32768L;
    }
    public static int S_IFLNK() {
        return (int)40960L;
    }
    public static int S_IFSOCK() {
        return (int)49152L;
    }
    public static int S_IFWHT() {
        return (int)57344L;
    }
    public static int S_IRWXU() {
        return (int)448L;
    }
    public static int S_IRUSR() {
        return (int)256L;
    }
    public static int S_IWUSR() {
        return (int)128L;
    }
    public static int S_IXUSR() {
        return (int)64L;
    }
    public static int S_IRWXG() {
        return (int)56L;
    }
    public static int S_IRGRP() {
        return (int)32L;
    }
    public static int S_IWGRP() {
        return (int)16L;
    }
    public static int S_IXGRP() {
        return (int)8L;
    }
    public static int S_IRWXO() {
        return (int)7L;
    }
    public static int S_IROTH() {
        return (int)4L;
    }
    public static int S_IWOTH() {
        return (int)2L;
    }
    public static int S_IXOTH() {
        return (int)1L;
    }
    public static int S_ISUID() {
        return (int)2048L;
    }
    public static int S_ISGID() {
        return (int)1024L;
    }
    public static int S_ISVTX() {
        return (int)512L;
    }
    public static int S_BLKSIZE() {
        return (int)512L;
    }
    public static int UF_SETTABLE() {
        return (int)65535L;
    }
    public static int UF_NODUMP() {
        return (int)1L;
    }
    public static int UF_IMMUTABLE() {
        return (int)2L;
    }
    public static int UF_APPEND() {
        return (int)4L;
    }
    public static int UF_OPAQUE() {
        return (int)8L;
    }
    public static int UF_COMPRESSED() {
        return (int)32L;
    }
    public static int UF_TRACKED() {
        return (int)64L;
    }
    public static int UF_DATAVAULT() {
        return (int)128L;
    }
    public static int UF_HIDDEN() {
        return (int)32768L;
    }
    public static int SF_SUPPORTED() {
        return (int)10420224L;
    }
    public static int SF_SETTABLE() {
        return (int)1073676288L;
    }
    public static int SF_ARCHIVED() {
        return (int)65536L;
    }
    public static int SF_IMMUTABLE() {
        return (int)131072L;
    }
    public static int SF_APPEND() {
        return (int)262144L;
    }
    public static int SF_RESTRICTED() {
        return (int)524288L;
    }
    public static int SF_NOUNLINK() {
        return (int)1048576L;
    }
    public static int SF_FIRMLINK() {
        return (int)8388608L;
    }
    public static int SF_DATALESS() {
        return (int)1073741824L;
    }
    public static int EF_MAY_SHARE_BLOCKS() {
        return (int)1L;
    }
    public static int EF_NO_XATTRS() {
        return (int)2L;
    }
    public static int EF_IS_SYNC_ROOT() {
        return (int)4L;
    }
    public static int EF_IS_PURGEABLE() {
        return (int)8L;
    }
    public static int EF_IS_SPARSE() {
        return (int)16L;
    }
    public static int EF_IS_SYNTHETIC() {
        return (int)32L;
    }
    public static int FUSE_IOCTL_MAX_IOV() {
        return (int)256L;
    }
    public static int O_RDONLY() {
        return (int)0L;
    }
    public static int O_WRONLY() {
        return (int)1L;
    }
    public static int O_RDWR() {
        return (int)2L;
    }
    public static int O_ACCMODE() {
        return (int)3L;
    }
    public static int FREAD() {
        return (int)1L;
    }
    public static int FWRITE() {
        return (int)2L;
    }
    public static int O_NONBLOCK() {
        return (int)4L;
    }
    public static int O_APPEND() {
        return (int)8L;
    }
    public static int O_SYNC() {
        return (int)128L;
    }
    public static int O_SHLOCK() {
        return (int)16L;
    }
    public static int O_EXLOCK() {
        return (int)32L;
    }
    public static int O_ASYNC() {
        return (int)64L;
    }
    public static int O_NOFOLLOW() {
        return (int)256L;
    }
    public static int O_CREAT() {
        return (int)512L;
    }
    public static int O_TRUNC() {
        return (int)1024L;
    }
    public static int O_EXCL() {
        return (int)2048L;
    }
    public static int O_EVTONLY() {
        return (int)32768L;
    }
    public static int O_NOCTTY() {
        return (int)131072L;
    }
    public static int O_DIRECTORY() {
        return (int)1048576L;
    }
    public static int O_SYMLINK() {
        return (int)2097152L;
    }
    public static int O_DSYNC() {
        return (int)4194304L;
    }
    public static int O_CLOEXEC() {
        return (int)16777216L;
    }
    public static int O_NOFOLLOW_ANY() {
        return (int)536870912L;
    }
    public static int AT_EACCESS() {
        return (int)16L;
    }
    public static int AT_SYMLINK_NOFOLLOW() {
        return (int)32L;
    }
    public static int AT_SYMLINK_FOLLOW() {
        return (int)64L;
    }
    public static int AT_REMOVEDIR() {
        return (int)128L;
    }
    public static int AT_REALDEV() {
        return (int)512L;
    }
    public static int AT_FDONLY() {
        return (int)1024L;
    }
    public static int AT_SYMLINK_NOFOLLOW_ANY() {
        return (int)2048L;
    }
    public static int O_DP_GETRAWENCRYPTED() {
        return (int)1L;
    }
    public static int O_DP_GETRAWUNENCRYPTED() {
        return (int)2L;
    }
    public static int CPF_OVERWRITE() {
        return (int)1L;
    }
    public static int CPF_IGNORE_MODE() {
        return (int)2L;
    }
    public static int F_DUPFD() {
        return (int)0L;
    }
    public static int F_GETFD() {
        return (int)1L;
    }
    public static int F_SETFD() {
        return (int)2L;
    }
    public static int F_GETFL() {
        return (int)3L;
    }
    public static int F_SETFL() {
        return (int)4L;
    }
    public static int F_GETOWN() {
        return (int)5L;
    }
    public static int F_SETOWN() {
        return (int)6L;
    }
    public static int F_GETLK() {
        return (int)7L;
    }
    public static int F_SETLK() {
        return (int)8L;
    }
    public static int F_SETLKW() {
        return (int)9L;
    }
    public static int F_SETLKWTIMEOUT() {
        return (int)10L;
    }
    public static int F_FLUSH_DATA() {
        return (int)40L;
    }
    public static int F_CHKCLEAN() {
        return (int)41L;
    }
    public static int F_PREALLOCATE() {
        return (int)42L;
    }
    public static int F_SETSIZE() {
        return (int)43L;
    }
    public static int F_RDADVISE() {
        return (int)44L;
    }
    public static int F_RDAHEAD() {
        return (int)45L;
    }
    public static int F_NOCACHE() {
        return (int)48L;
    }
    public static int F_LOG2PHYS() {
        return (int)49L;
    }
    public static int F_GETPATH() {
        return (int)50L;
    }
    public static int F_FULLFSYNC() {
        return (int)51L;
    }
    public static int F_PATHPKG_CHECK() {
        return (int)52L;
    }
    public static int F_FREEZE_FS() {
        return (int)53L;
    }
    public static int F_THAW_FS() {
        return (int)54L;
    }
    public static int F_GLOBAL_NOCACHE() {
        return (int)55L;
    }
    public static int F_ADDSIGS() {
        return (int)59L;
    }
    public static int F_ADDFILESIGS() {
        return (int)61L;
    }
    public static int F_NODIRECT() {
        return (int)62L;
    }
    public static int F_GETPROTECTIONCLASS() {
        return (int)63L;
    }
    public static int F_SETPROTECTIONCLASS() {
        return (int)64L;
    }
    public static int F_LOG2PHYS_EXT() {
        return (int)65L;
    }
    public static int F_GETLKPID() {
        return (int)66L;
    }
    public static int F_SETBACKINGSTORE() {
        return (int)70L;
    }
    public static int F_GETPATH_MTMINFO() {
        return (int)71L;
    }
    public static int F_GETCODEDIR() {
        return (int)72L;
    }
    public static int F_SETNOSIGPIPE() {
        return (int)73L;
    }
    public static int F_GETNOSIGPIPE() {
        return (int)74L;
    }
    public static int F_TRANSCODEKEY() {
        return (int)75L;
    }
    public static int F_SINGLE_WRITER() {
        return (int)76L;
    }
    public static int F_GETPROTECTIONLEVEL() {
        return (int)77L;
    }
    public static int F_FINDSIGS() {
        return (int)78L;
    }
    public static int F_ADDFILESIGS_FOR_DYLD_SIM() {
        return (int)83L;
    }
    public static int F_BARRIERFSYNC() {
        return (int)85L;
    }
    public static int F_ADDFILESIGS_RETURN() {
        return (int)97L;
    }
    public static int F_CHECK_LV() {
        return (int)98L;
    }
    public static int F_PUNCHHOLE() {
        return (int)99L;
    }
    public static int F_TRIM_ACTIVE_FILE() {
        return (int)100L;
    }
    public static int F_SPECULATIVE_READ() {
        return (int)101L;
    }
    public static int F_GETPATH_NOFIRMLINK() {
        return (int)102L;
    }
    public static int F_ADDFILESIGS_INFO() {
        return (int)103L;
    }
    public static int F_ADDFILESUPPL() {
        return (int)104L;
    }
    public static int F_GETSIGSINFO() {
        return (int)105L;
    }
    public static int F_FSRESERVED() {
        return (int)106L;
    }
    public static int FCNTL_FS_SPECIFIC_BASE() {
        return (int)65536L;
    }
    public static int F_DUPFD_CLOEXEC() {
        return (int)67L;
    }
    public static int FD_CLOEXEC() {
        return (int)1L;
    }
    public static int F_RDLCK() {
        return (int)1L;
    }
    public static int F_UNLCK() {
        return (int)2L;
    }
    public static int F_WRLCK() {
        return (int)3L;
    }
    public static int SEEK_SET() {
        return (int)0L;
    }
    public static int SEEK_CUR() {
        return (int)1L;
    }
    public static int SEEK_END() {
        return (int)2L;
    }
    public static int SEEK_HOLE() {
        return (int)3L;
    }
    public static int SEEK_DATA() {
        return (int)4L;
    }
    public static int F_ALLOCATECONTIG() {
        return (int)2L;
    }
    public static int F_ALLOCATEALL() {
        return (int)4L;
    }
    public static int F_PEOFPOSMODE() {
        return (int)3L;
    }
    public static int F_VOLPOSMODE() {
        return (int)4L;
    }
    public static int USER_FSIGNATURES_CDHASH_LEN() {
        return (int)20L;
    }
    public static int GETSIGSINFO_PLATFORM_BINARY() {
        return (int)1L;
    }
    public static int LOCK_SH() {
        return (int)1L;
    }
    public static int LOCK_EX() {
        return (int)2L;
    }
    public static int LOCK_NB() {
        return (int)4L;
    }
    public static int LOCK_UN() {
        return (int)8L;
    }
    public static int O_ALERT() {
        return (int)536870912L;
    }
    public static int _FORTIFY_SOURCE() {
        return (int)2L;
    }
    public static int TIME_UTC() {
        return (int)1L;
    }
    public static int ST_RDONLY() {
        return (int)1L;
    }
    public static int ST_NOSUID() {
        return (int)2L;
    }
    public static int BSD() {
        return (int)199506L;
    }
    public static int BSD4_3() {
        return (int)1L;
    }
    public static int BSD4_4() {
        return (int)1L;
    }
    public static int NeXTBSD() {
        return (int)1995064L;
    }
    public static int NeXTBSD4_0() {
        return (int)0L;
    }
    public static int CHILD_MAX() {
        return (int)266L;
    }
    public static int LINK_MAX() {
        return (int)32767L;
    }
    public static int MAX_CANON() {
        return (int)1024L;
    }
    public static int MAX_INPUT() {
        return (int)1024L;
    }
    public static int NAME_MAX() {
        return (int)255L;
    }
    public static int NGROUPS_MAX() {
        return (int)16L;
    }
    public static int OPEN_MAX() {
        return (int)10240L;
    }
    public static int PATH_MAX() {
        return (int)1024L;
    }
    public static int PIPE_BUF() {
        return (int)512L;
    }
    public static int BC_BASE_MAX() {
        return (int)99L;
    }
    public static int BC_DIM_MAX() {
        return (int)2048L;
    }
    public static int BC_SCALE_MAX() {
        return (int)99L;
    }
    public static int BC_STRING_MAX() {
        return (int)1000L;
    }
    public static int CHARCLASS_NAME_MAX() {
        return (int)14L;
    }
    public static int COLL_WEIGHTS_MAX() {
        return (int)2L;
    }
    public static int EQUIV_CLASS_MAX() {
        return (int)2L;
    }
    public static int EXPR_NEST_MAX() {
        return (int)32L;
    }
    public static int LINE_MAX() {
        return (int)2048L;
    }
    public static int RE_DUP_MAX() {
        return (int)255L;
    }
    public static int NZERO() {
        return (int)20L;
    }
    public static int MAXCOMLEN() {
        return (int)16L;
    }
    public static int MAXINTERP() {
        return (int)64L;
    }
    public static int MAXLOGNAME() {
        return (int)255L;
    }
    public static int NOFILE() {
        return (int)256L;
    }
    public static int NOGROUP() {
        return (int)65535L;
    }
    public static int MAXHOSTNAMELEN() {
        return (int)256L;
    }
    public static int MAXDOMNAMELEN() {
        return (int)256L;
    }
    public static int NBPG() {
        return (int)4096L;
    }
    public static int PGSHIFT() {
        return (int)12L;
    }
    public static int DEV_BSIZE() {
        return (int)512L;
    }
    public static int DEV_BSHIFT() {
        return (int)9L;
    }
    public static int BLKDEV_IOSIZE() {
        return (int)2048L;
    }
    public static int CLSIZE() {
        return (int)1L;
    }
    public static int CLSIZELOG2() {
        return (int)0L;
    }
    public static int MSIZESHIFT() {
        return (int)8L;
    }
    public static int MCLSHIFT() {
        return (int)11L;
    }
    public static int MBIGCLSHIFT() {
        return (int)12L;
    }
    public static int M16KCLSHIFT() {
        return (int)14L;
    }
    public static int __DARWIN_CLK_TCK() {
        return (int)100L;
    }
    public static int CHAR_BIT() {
        return (int)8L;
    }
    public static int MB_LEN_MAX() {
        return (int)6L;
    }
    public static int SCHAR_MAX() {
        return (int)127L;
    }
    public static int UCHAR_MAX() {
        return (int)255L;
    }
    public static int CHAR_MAX() {
        return (int)127L;
    }
    public static int USHRT_MAX() {
        return (int)65535L;
    }
    public static int SHRT_MAX() {
        return (int)32767L;
    }
    public static int INT_MAX() {
        return (int)2147483647L;
    }
    public static int LONG_BIT() {
        return (int)64L;
    }
    public static int WORD_BIT() {
        return (int)32L;
    }
    public static int _POSIX_ARG_MAX() {
        return (int)4096L;
    }
    public static int _POSIX_CHILD_MAX() {
        return (int)25L;
    }
    public static int _POSIX_LINK_MAX() {
        return (int)8L;
    }
    public static int _POSIX_MAX_CANON() {
        return (int)255L;
    }
    public static int _POSIX_MAX_INPUT() {
        return (int)255L;
    }
    public static int _POSIX_NAME_MAX() {
        return (int)14L;
    }
    public static int _POSIX_NGROUPS_MAX() {
        return (int)8L;
    }
    public static int _POSIX_OPEN_MAX() {
        return (int)20L;
    }
    public static int _POSIX_PATH_MAX() {
        return (int)256L;
    }
    public static int _POSIX_PIPE_BUF() {
        return (int)512L;
    }
    public static int _POSIX_SSIZE_MAX() {
        return (int)32767L;
    }
    public static int _POSIX_STREAM_MAX() {
        return (int)8L;
    }
    public static int _POSIX_TZNAME_MAX() {
        return (int)6L;
    }
    public static int _POSIX2_BC_BASE_MAX() {
        return (int)99L;
    }
    public static int _POSIX2_BC_DIM_MAX() {
        return (int)2048L;
    }
    public static int _POSIX2_BC_SCALE_MAX() {
        return (int)99L;
    }
    public static int _POSIX2_BC_STRING_MAX() {
        return (int)1000L;
    }
    public static int _POSIX2_EQUIV_CLASS_MAX() {
        return (int)2L;
    }
    public static int _POSIX2_EXPR_NEST_MAX() {
        return (int)32L;
    }
    public static int _POSIX2_LINE_MAX() {
        return (int)2048L;
    }
    public static int _POSIX2_RE_DUP_MAX() {
        return (int)255L;
    }
    public static int _POSIX_AIO_LISTIO_MAX() {
        return (int)2L;
    }
    public static int _POSIX_AIO_MAX() {
        return (int)1L;
    }
    public static int _POSIX_DELAYTIMER_MAX() {
        return (int)32L;
    }
    public static int _POSIX_MQ_OPEN_MAX() {
        return (int)8L;
    }
    public static int _POSIX_MQ_PRIO_MAX() {
        return (int)32L;
    }
    public static int _POSIX_RTSIG_MAX() {
        return (int)8L;
    }
    public static int _POSIX_SEM_NSEMS_MAX() {
        return (int)256L;
    }
    public static int _POSIX_SEM_VALUE_MAX() {
        return (int)32767L;
    }
    public static int _POSIX_SIGQUEUE_MAX() {
        return (int)32L;
    }
    public static int _POSIX_TIMER_MAX() {
        return (int)32L;
    }
    public static int _POSIX_CLOCKRES_MIN() {
        return (int)20000000L;
    }
    public static int _POSIX_THREAD_DESTRUCTOR_ITERATIONS() {
        return (int)4L;
    }
    public static int _POSIX_THREAD_KEYS_MAX() {
        return (int)128L;
    }
    public static int _POSIX_THREAD_THREADS_MAX() {
        return (int)64L;
    }
    public static int PTHREAD_DESTRUCTOR_ITERATIONS() {
        return (int)4L;
    }
    public static int PTHREAD_KEYS_MAX() {
        return (int)512L;
    }
    public static int PTHREAD_STACK_MIN() {
        return (int)16384L;
    }
    public static int _POSIX_HOST_NAME_MAX() {
        return (int)255L;
    }
    public static int _POSIX_LOGIN_NAME_MAX() {
        return (int)9L;
    }
    public static int _POSIX_SS_REPL_MAX() {
        return (int)4L;
    }
    public static int _POSIX_SYMLINK_MAX() {
        return (int)255L;
    }
    public static int _POSIX_SYMLOOP_MAX() {
        return (int)8L;
    }
    public static int _POSIX_TRACE_EVENT_NAME_MAX() {
        return (int)30L;
    }
    public static int _POSIX_TRACE_NAME_MAX() {
        return (int)8L;
    }
    public static int _POSIX_TRACE_SYS_MAX() {
        return (int)8L;
    }
    public static int _POSIX_TRACE_USER_EVENT_MAX() {
        return (int)32L;
    }
    public static int _POSIX_TTY_NAME_MAX() {
        return (int)9L;
    }
    public static int _POSIX2_CHARCLASS_NAME_MAX() {
        return (int)14L;
    }
    public static int _POSIX2_COLL_WEIGHTS_MAX() {
        return (int)2L;
    }
    public static int PASS_MAX() {
        return (int)128L;
    }
    public static int NL_ARGMAX() {
        return (int)9L;
    }
    public static int NL_LANGMAX() {
        return (int)14L;
    }
    public static int NL_MSGMAX() {
        return (int)32767L;
    }
    public static int NL_NMAX() {
        return (int)1L;
    }
    public static int NL_SETMAX() {
        return (int)255L;
    }
    public static int NL_TEXTMAX() {
        return (int)2048L;
    }
    public static int _XOPEN_IOV_MAX() {
        return (int)16L;
    }
    public static int IOV_MAX() {
        return (int)1024L;
    }
    public static int _XOPEN_NAME_MAX() {
        return (int)255L;
    }
    public static int _XOPEN_PATH_MAX() {
        return (int)1024L;
    }
    public static int __DARWIN_NSIG() {
        return (int)32L;
    }
    public static int _ARM_SIGNAL_() {
        return (int)1L;
    }
    public static int SIGHUP() {
        return (int)1L;
    }
    public static int SIGINT() {
        return (int)2L;
    }
    public static int SIGQUIT() {
        return (int)3L;
    }
    public static int SIGILL() {
        return (int)4L;
    }
    public static int SIGTRAP() {
        return (int)5L;
    }
    public static int SIGABRT() {
        return (int)6L;
    }
    public static int SIGEMT() {
        return (int)7L;
    }
    public static int SIGFPE() {
        return (int)8L;
    }
    public static int SIGKILL() {
        return (int)9L;
    }
    public static int SIGBUS() {
        return (int)10L;
    }
    public static int SIGSEGV() {
        return (int)11L;
    }
    public static int SIGSYS() {
        return (int)12L;
    }
    public static int SIGPIPE() {
        return (int)13L;
    }
    public static int SIGALRM() {
        return (int)14L;
    }
    public static int SIGTERM() {
        return (int)15L;
    }
    public static int SIGURG() {
        return (int)16L;
    }
    public static int SIGSTOP() {
        return (int)17L;
    }
    public static int SIGTSTP() {
        return (int)18L;
    }
    public static int SIGCONT() {
        return (int)19L;
    }
    public static int SIGCHLD() {
        return (int)20L;
    }
    public static int SIGTTIN() {
        return (int)21L;
    }
    public static int SIGTTOU() {
        return (int)22L;
    }
    public static int SIGIO() {
        return (int)23L;
    }
    public static int SIGXCPU() {
        return (int)24L;
    }
    public static int SIGXFSZ() {
        return (int)25L;
    }
    public static int SIGVTALRM() {
        return (int)26L;
    }
    public static int SIGPROF() {
        return (int)27L;
    }
    public static int SIGWINCH() {
        return (int)28L;
    }
    public static int SIGINFO() {
        return (int)29L;
    }
    public static int SIGUSR1() {
        return (int)30L;
    }
    public static int SIGUSR2() {
        return (int)31L;
    }
    public static int __DARWIN_OPAQUE_ARM_THREAD_STATE64() {
        return (int)0L;
    }
    public static int SIGEV_NONE() {
        return (int)0L;
    }
    public static int SIGEV_SIGNAL() {
        return (int)1L;
    }
    public static int SIGEV_THREAD() {
        return (int)3L;
    }
    public static int ILL_NOOP() {
        return (int)0L;
    }
    public static int ILL_ILLOPC() {
        return (int)1L;
    }
    public static int ILL_ILLTRP() {
        return (int)2L;
    }
    public static int ILL_PRVOPC() {
        return (int)3L;
    }
    public static int ILL_ILLOPN() {
        return (int)4L;
    }
    public static int ILL_ILLADR() {
        return (int)5L;
    }
    public static int ILL_PRVREG() {
        return (int)6L;
    }
    public static int ILL_COPROC() {
        return (int)7L;
    }
    public static int ILL_BADSTK() {
        return (int)8L;
    }
    public static int FPE_NOOP() {
        return (int)0L;
    }
    public static int FPE_FLTDIV() {
        return (int)1L;
    }
    public static int FPE_FLTOVF() {
        return (int)2L;
    }
    public static int FPE_FLTUND() {
        return (int)3L;
    }
    public static int FPE_FLTRES() {
        return (int)4L;
    }
    public static int FPE_FLTINV() {
        return (int)5L;
    }
    public static int FPE_FLTSUB() {
        return (int)6L;
    }
    public static int FPE_INTDIV() {
        return (int)7L;
    }
    public static int FPE_INTOVF() {
        return (int)8L;
    }
    public static int SEGV_NOOP() {
        return (int)0L;
    }
    public static int SEGV_MAPERR() {
        return (int)1L;
    }
    public static int SEGV_ACCERR() {
        return (int)2L;
    }
    public static int BUS_NOOP() {
        return (int)0L;
    }
    public static int BUS_ADRALN() {
        return (int)1L;
    }
    public static int BUS_ADRERR() {
        return (int)2L;
    }
    public static int BUS_OBJERR() {
        return (int)3L;
    }
    public static int TRAP_BRKPT() {
        return (int)1L;
    }
    public static int TRAP_TRACE() {
        return (int)2L;
    }
    public static int CLD_NOOP() {
        return (int)0L;
    }
    public static int CLD_EXITED() {
        return (int)1L;
    }
    public static int CLD_KILLED() {
        return (int)2L;
    }
    public static int CLD_DUMPED() {
        return (int)3L;
    }
    public static int CLD_TRAPPED() {
        return (int)4L;
    }
    public static int CLD_STOPPED() {
        return (int)5L;
    }
    public static int CLD_CONTINUED() {
        return (int)6L;
    }
    public static int POLL_IN() {
        return (int)1L;
    }
    public static int POLL_OUT() {
        return (int)2L;
    }
    public static int POLL_MSG() {
        return (int)3L;
    }
    public static int POLL_ERR() {
        return (int)4L;
    }
    public static int POLL_PRI() {
        return (int)5L;
    }
    public static int POLL_HUP() {
        return (int)6L;
    }
    public static int SA_ONSTACK() {
        return (int)1L;
    }
    public static int SA_RESTART() {
        return (int)2L;
    }
    public static int SA_RESETHAND() {
        return (int)4L;
    }
    public static int SA_NOCLDSTOP() {
        return (int)8L;
    }
    public static int SA_NODEFER() {
        return (int)16L;
    }
    public static int SA_NOCLDWAIT() {
        return (int)32L;
    }
    public static int SA_SIGINFO() {
        return (int)64L;
    }
    public static int SA_USERTRAMP() {
        return (int)256L;
    }
    public static int SA_64REGSET() {
        return (int)512L;
    }
    public static int SIG_BLOCK() {
        return (int)1L;
    }
    public static int SIG_UNBLOCK() {
        return (int)2L;
    }
    public static int SIG_SETMASK() {
        return (int)3L;
    }
    public static int SI_USER() {
        return (int)65537L;
    }
    public static int SI_QUEUE() {
        return (int)65538L;
    }
    public static int SI_TIMER() {
        return (int)65539L;
    }
    public static int SI_ASYNCIO() {
        return (int)65540L;
    }
    public static int SI_MESGQ() {
        return (int)65541L;
    }
    public static int SS_ONSTACK() {
        return (int)1L;
    }
    public static int SS_DISABLE() {
        return (int)4L;
    }
    public static int MINSIGSTKSZ() {
        return (int)32768L;
    }
    public static int SIGSTKSZ() {
        return (int)131072L;
    }
    public static int PSWP() {
        return (int)0L;
    }
    public static int PVM() {
        return (int)4L;
    }
    public static int PINOD() {
        return (int)8L;
    }
    public static int PRIBIO() {
        return (int)16L;
    }
    public static int PVFS() {
        return (int)20L;
    }
    public static int PZERO() {
        return (int)22L;
    }
    public static int PSOCK() {
        return (int)24L;
    }
    public static int PWAIT() {
        return (int)32L;
    }
    public static int PLOCK() {
        return (int)36L;
    }
    public static int PPAUSE() {
        return (int)40L;
    }
    public static int PUSER() {
        return (int)50L;
    }
    public static int MAXPRI() {
        return (int)127L;
    }
    public static int PRIMASK() {
        return (int)255L;
    }
    public static int PCATCH() {
        return (int)256L;
    }
    public static int PTTYBLOCK() {
        return (int)512L;
    }
    public static int PDROP() {
        return (int)1024L;
    }
    public static int PSPIN() {
        return (int)2048L;
    }
    public static int CMASK() {
        return (int)18L;
    }
    public static int CBLOCK() {
        return (int)64L;
    }
    public static int MAXFRAG() {
        return (int)8L;
    }
    public static int MAXSYMLINKS() {
        return (int)32L;
    }
    public static int FSHIFT() {
        return (int)11L;
    }
    public static int MAX_AUDIT_RECORDS() {
        return (int)20L;
    }
    public static int AUDIT_HARD_LIMIT_FREE_BLOCKS() {
        return (int)4L;
    }
    public static int AUDIT_TRIGGER_MIN() {
        return (int)1L;
    }
    public static int AUDIT_TRIGGER_LOW_SPACE() {
        return (int)1L;
    }
    public static int AUDIT_TRIGGER_ROTATE_KERNEL() {
        return (int)2L;
    }
    public static int AUDIT_TRIGGER_READ_FILE() {
        return (int)3L;
    }
    public static int AUDIT_TRIGGER_CLOSE_AND_DIE() {
        return (int)4L;
    }
    public static int AUDIT_TRIGGER_NO_SPACE() {
        return (int)5L;
    }
    public static int AUDIT_TRIGGER_ROTATE_USER() {
        return (int)6L;
    }
    public static int AUDIT_TRIGGER_INITIALIZE() {
        return (int)7L;
    }
    public static int AUDIT_TRIGGER_EXPIRE_TRAILS() {
        return (int)8L;
    }
    public static int AUDIT_TRIGGER_MAX() {
        return (int)8L;
    }
    public static int AU_DEFAUDITSID() {
        return (int)0L;
    }
    public static int AUC_UNSET() {
        return (int)0L;
    }
    public static int AUC_AUDITING() {
        return (int)1L;
    }
    public static int AUC_NOAUDIT() {
        return (int)2L;
    }
    public static int A_OLDGETPOLICY() {
        return (int)2L;
    }
    public static int A_OLDSETPOLICY() {
        return (int)3L;
    }
    public static int A_GETKMASK() {
        return (int)4L;
    }
    public static int A_SETKMASK() {
        return (int)5L;
    }
    public static int A_OLDGETQCTRL() {
        return (int)6L;
    }
    public static int A_OLDSETQCTRL() {
        return (int)7L;
    }
    public static int A_GETCWD() {
        return (int)8L;
    }
    public static int A_GETCAR() {
        return (int)9L;
    }
    public static int A_GETSTAT() {
        return (int)12L;
    }
    public static int A_SETSTAT() {
        return (int)13L;
    }
    public static int A_SETUMASK() {
        return (int)14L;
    }
    public static int A_SETSMASK() {
        return (int)15L;
    }
    public static int A_OLDGETCOND() {
        return (int)20L;
    }
    public static int A_OLDSETCOND() {
        return (int)21L;
    }
    public static int A_GETCLASS() {
        return (int)22L;
    }
    public static int A_SETCLASS() {
        return (int)23L;
    }
    public static int A_GETPINFO() {
        return (int)24L;
    }
    public static int A_SETPMASK() {
        return (int)25L;
    }
    public static int A_SETFSIZE() {
        return (int)26L;
    }
    public static int A_GETFSIZE() {
        return (int)27L;
    }
    public static int A_GETPINFO_ADDR() {
        return (int)28L;
    }
    public static int A_GETKAUDIT() {
        return (int)29L;
    }
    public static int A_SETKAUDIT() {
        return (int)30L;
    }
    public static int A_SENDTRIGGER() {
        return (int)31L;
    }
    public static int A_GETSINFO_ADDR() {
        return (int)32L;
    }
    public static int A_GETPOLICY() {
        return (int)33L;
    }
    public static int A_SETPOLICY() {
        return (int)34L;
    }
    public static int A_GETQCTRL() {
        return (int)35L;
    }
    public static int A_SETQCTRL() {
        return (int)36L;
    }
    public static int A_GETCOND() {
        return (int)37L;
    }
    public static int A_SETCOND() {
        return (int)38L;
    }
    public static int A_GETSFLAGS() {
        return (int)39L;
    }
    public static int A_SETSFLAGS() {
        return (int)40L;
    }
    public static int A_GETCTLMODE() {
        return (int)41L;
    }
    public static int A_SETCTLMODE() {
        return (int)42L;
    }
    public static int A_GETEXPAFTER() {
        return (int)43L;
    }
    public static int A_SETEXPAFTER() {
        return (int)44L;
    }
    public static int AUDIT_CNT() {
        return (int)1L;
    }
    public static int AUDIT_AHLT() {
        return (int)2L;
    }
    public static int AUDIT_ARGV() {
        return (int)4L;
    }
    public static int AUDIT_ARGE() {
        return (int)8L;
    }
    public static int AUDIT_SEQ() {
        return (int)16L;
    }
    public static int AUDIT_WINDATA() {
        return (int)32L;
    }
    public static int AUDIT_USER() {
        return (int)64L;
    }
    public static int AUDIT_GROUP() {
        return (int)128L;
    }
    public static int AUDIT_TRAIL() {
        return (int)256L;
    }
    public static int AUDIT_PATH() {
        return (int)512L;
    }
    public static int AUDIT_SCNT() {
        return (int)1024L;
    }
    public static int AUDIT_PUBLIC() {
        return (int)2048L;
    }
    public static int AUDIT_ZONENAME() {
        return (int)4096L;
    }
    public static int AUDIT_PERZONE() {
        return (int)8192L;
    }
    public static int AQ_HIWATER() {
        return (int)100L;
    }
    public static int AQ_MAXHIGH() {
        return (int)10000L;
    }
    public static int AQ_LOWATER() {
        return (int)10L;
    }
    public static int AQ_MAXBUFSZ() {
        return (int)1048576L;
    }
    public static int AU_FS_MINFREE() {
        return (int)20L;
    }
    public static int AU_IPv4() {
        return (int)4L;
    }
    public static int AU_IPv6() {
        return (int)16L;
    }
    public static int AU_CLASS_MASK_RESERVED() {
        return (int)268435456L;
    }
    public static int TRUE() {
        return (int)1L;
    }
    public static int FALSE() {
        return (int)0L;
    }
    public static int MACH_PORT_NULL() {
        return (int)0L;
    }
    public static int MACH_PORT_TYPE_SPREQUEST() {
        return (int)1073741824L;
    }
    public static int MACH_PORT_TYPE_SPREQUEST_DELAYED() {
        return (int)536870912L;
    }
    public static int MACH_PORT_SRIGHTS_NONE() {
        return (int)0L;
    }
    public static int MACH_PORT_SRIGHTS_PRESENT() {
        return (int)1L;
    }
    public static int MACH_PORT_STATUS_FLAG_TEMPOWNER() {
        return (int)1L;
    }
    public static int MACH_PORT_STATUS_FLAG_GUARDED() {
        return (int)2L;
    }
    public static int MACH_PORT_STATUS_FLAG_STRICT_GUARD() {
        return (int)4L;
    }
    public static int MACH_PORT_STATUS_FLAG_IMP_DONATION() {
        return (int)8L;
    }
    public static int MACH_PORT_STATUS_FLAG_REVIVE() {
        return (int)16L;
    }
    public static int MACH_PORT_STATUS_FLAG_TASKPTR() {
        return (int)32L;
    }
    public static int MACH_PORT_STATUS_FLAG_GUARD_IMMOVABLE_RECEIVE() {
        return (int)64L;
    }
    public static int MACH_PORT_STATUS_FLAG_NO_GRANT() {
        return (int)128L;
    }
    public static int MACH_PORT_LIMITS_INFO() {
        return (int)1L;
    }
    public static int MACH_PORT_RECEIVE_STATUS() {
        return (int)2L;
    }
    public static int MACH_PORT_DNREQUESTS_SIZE() {
        return (int)3L;
    }
    public static int MACH_PORT_TEMPOWNER() {
        return (int)4L;
    }
    public static int MACH_PORT_IMPORTANCE_RECEIVER() {
        return (int)5L;
    }
    public static int MACH_PORT_DENAP_RECEIVER() {
        return (int)6L;
    }
    public static int MACH_PORT_INFO_EXT() {
        return (int)7L;
    }
    public static int MACH_PORT_GUARD_INFO() {
        return (int)8L;
    }
    public static int MACH_PORT_DNREQUESTS_SIZE_COUNT() {
        return (int)1L;
    }
    public static int MACH_SERVICE_PORT_INFO_STRING_NAME_MAX_BUF_LEN() {
        return (int)255L;
    }
    public static int MPO_CONTEXT_AS_GUARD() {
        return (int)1L;
    }
    public static int MPO_QLIMIT() {
        return (int)2L;
    }
    public static int MPO_TEMPOWNER() {
        return (int)4L;
    }
    public static int MPO_IMPORTANCE_RECEIVER() {
        return (int)8L;
    }
    public static int MPO_INSERT_SEND_RIGHT() {
        return (int)16L;
    }
    public static int MPO_STRICT() {
        return (int)32L;
    }
    public static int MPO_DENAP_RECEIVER() {
        return (int)64L;
    }
    public static int MPO_IMMOVABLE_RECEIVE() {
        return (int)128L;
    }
    public static int MPO_FILTER_MSG() {
        return (int)256L;
    }
    public static int MPO_TG_BLOCK_TRACKING() {
        return (int)512L;
    }
    public static int MPO_SERVICE_PORT() {
        return (int)1024L;
    }
    public static int MPO_CONNECTION_PORT() {
        return (int)2048L;
    }
    public static int GUARD_TYPE_MACH_PORT() {
        return (int)1L;
    }
    public static int MPG_STRICT() {
        return (int)1L;
    }
    public static int MPG_IMMOVABLE_RECEIVE() {
        return (int)2L;
    }
    public static int CRF_NOMEMBERD() {
        return (int)1L;
    }
    public static int CRF_MAC_ENFORCE() {
        return (int)2L;
    }
    public static int XUCRED_VERSION() {
        return (int)0L;
    }
    public static int ITIMER_REAL() {
        return (int)0L;
    }
    public static int ITIMER_VIRTUAL() {
        return (int)1L;
    }
    public static int ITIMER_PROF() {
        return (int)2L;
    }
    public static int DST_NONE() {
        return (int)0L;
    }
    public static int DST_USA() {
        return (int)1L;
    }
    public static int DST_AUST() {
        return (int)2L;
    }
    public static int DST_WET() {
        return (int)3L;
    }
    public static int DST_MET() {
        return (int)4L;
    }
    public static int DST_EET() {
        return (int)5L;
    }
    public static int DST_CAN() {
        return (int)6L;
    }
    public static int FSOPT_NOFOLLOW() {
        return (int)1L;
    }
    public static int FSOPT_NOINMEMUPDATE() {
        return (int)2L;
    }
    public static int FSOPT_REPORT_FULLSIZE() {
        return (int)4L;
    }
    public static int FSOPT_PACK_INVAL_ATTRS() {
        return (int)8L;
    }
    public static int FSOPT_ATTR_CMN_EXTENDED() {
        return (int)32L;
    }
    public static int FSOPT_RETURN_REALDEV() {
        return (int)512L;
    }
    public static int FSOPT_NOFOLLOW_ANY() {
        return (int)2048L;
    }
    public static int SEARCHFS_MAX_SEARCHPARMS() {
        return (int)4096L;
    }
    public static int ATTR_BIT_MAP_COUNT() {
        return (int)5L;
    }
    public static int VOL_CAPABILITIES_FORMAT() {
        return (int)0L;
    }
    public static int VOL_CAPABILITIES_INTERFACES() {
        return (int)1L;
    }
    public static int VOL_CAPABILITIES_RESERVED1() {
        return (int)2L;
    }
    public static int VOL_CAPABILITIES_RESERVED2() {
        return (int)3L;
    }
    public static int ATTR_MAX_BUFFER() {
        return (int)8192L;
    }
    public static int VOL_CAP_FMT_PERSISTENTOBJECTIDS() {
        return (int)1L;
    }
    public static int VOL_CAP_FMT_SYMBOLICLINKS() {
        return (int)2L;
    }
    public static int VOL_CAP_FMT_HARDLINKS() {
        return (int)4L;
    }
    public static int VOL_CAP_FMT_JOURNAL() {
        return (int)8L;
    }
    public static int VOL_CAP_FMT_JOURNAL_ACTIVE() {
        return (int)16L;
    }
    public static int VOL_CAP_FMT_NO_ROOT_TIMES() {
        return (int)32L;
    }
    public static int VOL_CAP_FMT_SPARSE_FILES() {
        return (int)64L;
    }
    public static int VOL_CAP_FMT_ZERO_RUNS() {
        return (int)128L;
    }
    public static int VOL_CAP_FMT_CASE_SENSITIVE() {
        return (int)256L;
    }
    public static int VOL_CAP_FMT_CASE_PRESERVING() {
        return (int)512L;
    }
    public static int VOL_CAP_FMT_FAST_STATFS() {
        return (int)1024L;
    }
    public static int VOL_CAP_FMT_2TB_FILESIZE() {
        return (int)2048L;
    }
    public static int VOL_CAP_FMT_OPENDENYMODES() {
        return (int)4096L;
    }
    public static int VOL_CAP_FMT_HIDDEN_FILES() {
        return (int)8192L;
    }
    public static int VOL_CAP_FMT_PATH_FROM_ID() {
        return (int)16384L;
    }
    public static int VOL_CAP_FMT_NO_VOLUME_SIZES() {
        return (int)32768L;
    }
    public static int VOL_CAP_FMT_DECMPFS_COMPRESSION() {
        return (int)65536L;
    }
    public static int VOL_CAP_FMT_64BIT_OBJECT_IDS() {
        return (int)131072L;
    }
    public static int VOL_CAP_FMT_DIR_HARDLINKS() {
        return (int)262144L;
    }
    public static int VOL_CAP_FMT_DOCUMENT_ID() {
        return (int)524288L;
    }
    public static int VOL_CAP_FMT_WRITE_GENERATION_COUNT() {
        return (int)1048576L;
    }
    public static int VOL_CAP_FMT_NO_IMMUTABLE_FILES() {
        return (int)2097152L;
    }
    public static int VOL_CAP_FMT_NO_PERMISSIONS() {
        return (int)4194304L;
    }
    public static int VOL_CAP_FMT_SHARED_SPACE() {
        return (int)8388608L;
    }
    public static int VOL_CAP_FMT_VOL_GROUPS() {
        return (int)16777216L;
    }
    public static int VOL_CAP_FMT_SEALED() {
        return (int)33554432L;
    }
    public static int VOL_CAP_INT_SEARCHFS() {
        return (int)1L;
    }
    public static int VOL_CAP_INT_ATTRLIST() {
        return (int)2L;
    }
    public static int VOL_CAP_INT_NFSEXPORT() {
        return (int)4L;
    }
    public static int VOL_CAP_INT_READDIRATTR() {
        return (int)8L;
    }
    public static int VOL_CAP_INT_EXCHANGEDATA() {
        return (int)16L;
    }
    public static int VOL_CAP_INT_COPYFILE() {
        return (int)32L;
    }
    public static int VOL_CAP_INT_ALLOCATE() {
        return (int)64L;
    }
    public static int VOL_CAP_INT_VOL_RENAME() {
        return (int)128L;
    }
    public static int VOL_CAP_INT_ADVLOCK() {
        return (int)256L;
    }
    public static int VOL_CAP_INT_FLOCK() {
        return (int)512L;
    }
    public static int VOL_CAP_INT_EXTENDED_SECURITY() {
        return (int)1024L;
    }
    public static int VOL_CAP_INT_USERACCESS() {
        return (int)2048L;
    }
    public static int VOL_CAP_INT_MANLOCK() {
        return (int)4096L;
    }
    public static int VOL_CAP_INT_NAMEDSTREAMS() {
        return (int)8192L;
    }
    public static int VOL_CAP_INT_EXTENDED_ATTR() {
        return (int)16384L;
    }
    public static int VOL_CAP_INT_CLONE() {
        return (int)65536L;
    }
    public static int VOL_CAP_INT_SNAPSHOT() {
        return (int)131072L;
    }
    public static int VOL_CAP_INT_RENAME_SWAP() {
        return (int)262144L;
    }
    public static int VOL_CAP_INT_RENAME_EXCL() {
        return (int)524288L;
    }
    public static int VOL_CAP_INT_RENAME_OPENFAIL() {
        return (int)1048576L;
    }
    public static int ATTR_CMN_NAME() {
        return (int)1L;
    }
    public static int ATTR_CMN_DEVID() {
        return (int)2L;
    }
    public static int ATTR_CMN_FSID() {
        return (int)4L;
    }
    public static int ATTR_CMN_OBJTYPE() {
        return (int)8L;
    }
    public static int ATTR_CMN_OBJTAG() {
        return (int)16L;
    }
    public static int ATTR_CMN_OBJID() {
        return (int)32L;
    }
    public static int ATTR_CMN_OBJPERMANENTID() {
        return (int)64L;
    }
    public static int ATTR_CMN_PAROBJID() {
        return (int)128L;
    }
    public static int ATTR_CMN_SCRIPT() {
        return (int)256L;
    }
    public static int ATTR_CMN_CRTIME() {
        return (int)512L;
    }
    public static int ATTR_CMN_MODTIME() {
        return (int)1024L;
    }
    public static int ATTR_CMN_CHGTIME() {
        return (int)2048L;
    }
    public static int ATTR_CMN_ACCTIME() {
        return (int)4096L;
    }
    public static int ATTR_CMN_BKUPTIME() {
        return (int)8192L;
    }
    public static int ATTR_CMN_FNDRINFO() {
        return (int)16384L;
    }
    public static int ATTR_CMN_OWNERID() {
        return (int)32768L;
    }
    public static int ATTR_CMN_GRPID() {
        return (int)65536L;
    }
    public static int ATTR_CMN_ACCESSMASK() {
        return (int)131072L;
    }
    public static int ATTR_CMN_FLAGS() {
        return (int)262144L;
    }
    public static int ATTR_CMN_GEN_COUNT() {
        return (int)524288L;
    }
    public static int ATTR_CMN_DOCUMENT_ID() {
        return (int)1048576L;
    }
    public static int ATTR_CMN_USERACCESS() {
        return (int)2097152L;
    }
    public static int ATTR_CMN_EXTENDED_SECURITY() {
        return (int)4194304L;
    }
    public static int ATTR_CMN_UUID() {
        return (int)8388608L;
    }
    public static int ATTR_CMN_GRPUUID() {
        return (int)16777216L;
    }
    public static int ATTR_CMN_FILEID() {
        return (int)33554432L;
    }
    public static int ATTR_CMN_PARENTID() {
        return (int)67108864L;
    }
    public static int ATTR_CMN_FULLPATH() {
        return (int)134217728L;
    }
    public static int ATTR_CMN_ADDEDTIME() {
        return (int)268435456L;
    }
    public static int ATTR_CMN_ERROR() {
        return (int)536870912L;
    }
    public static int ATTR_CMN_DATA_PROTECT_FLAGS() {
        return (int)1073741824L;
    }
    public static int ATTR_CMN_SETMASK() {
        return (int)1372061440L;
    }
    public static int ATTR_CMN_VOLSETMASK() {
        return (int)26368L;
    }
    public static int ATTR_VOL_FSTYPE() {
        return (int)1L;
    }
    public static int ATTR_VOL_SIGNATURE() {
        return (int)2L;
    }
    public static int ATTR_VOL_SIZE() {
        return (int)4L;
    }
    public static int ATTR_VOL_SPACEFREE() {
        return (int)8L;
    }
    public static int ATTR_VOL_SPACEAVAIL() {
        return (int)16L;
    }
    public static int ATTR_VOL_MINALLOCATION() {
        return (int)32L;
    }
    public static int ATTR_VOL_ALLOCATIONCLUMP() {
        return (int)64L;
    }
    public static int ATTR_VOL_IOBLOCKSIZE() {
        return (int)128L;
    }
    public static int ATTR_VOL_OBJCOUNT() {
        return (int)256L;
    }
    public static int ATTR_VOL_FILECOUNT() {
        return (int)512L;
    }
    public static int ATTR_VOL_DIRCOUNT() {
        return (int)1024L;
    }
    public static int ATTR_VOL_MAXOBJCOUNT() {
        return (int)2048L;
    }
    public static int ATTR_VOL_MOUNTPOINT() {
        return (int)4096L;
    }
    public static int ATTR_VOL_NAME() {
        return (int)8192L;
    }
    public static int ATTR_VOL_MOUNTFLAGS() {
        return (int)16384L;
    }
    public static int ATTR_VOL_MOUNTEDDEVICE() {
        return (int)32768L;
    }
    public static int ATTR_VOL_ENCODINGSUSED() {
        return (int)65536L;
    }
    public static int ATTR_VOL_CAPABILITIES() {
        return (int)131072L;
    }
    public static int ATTR_VOL_UUID() {
        return (int)262144L;
    }
    public static int ATTR_VOL_SPACEUSED() {
        return (int)8388608L;
    }
    public static int ATTR_VOL_QUOTA_SIZE() {
        return (int)268435456L;
    }
    public static int ATTR_VOL_RESERVED_SIZE() {
        return (int)536870912L;
    }
    public static int ATTR_VOL_ATTRIBUTES() {
        return (int)1073741824L;
    }
    public static int ATTR_DIR_LINKCOUNT() {
        return (int)1L;
    }
    public static int ATTR_DIR_ENTRYCOUNT() {
        return (int)2L;
    }
    public static int ATTR_DIR_MOUNTSTATUS() {
        return (int)4L;
    }
    public static int ATTR_DIR_ALLOCSIZE() {
        return (int)8L;
    }
    public static int ATTR_DIR_IOBLOCKSIZE() {
        return (int)16L;
    }
    public static int ATTR_DIR_DATALENGTH() {
        return (int)32L;
    }
    public static int DIR_MNTSTATUS_MNTPOINT() {
        return (int)1L;
    }
    public static int DIR_MNTSTATUS_TRIGGER() {
        return (int)2L;
    }
    public static int ATTR_DIR_VALIDMASK() {
        return (int)63L;
    }
    public static int ATTR_DIR_SETMASK() {
        return (int)0L;
    }
    public static int ATTR_FILE_LINKCOUNT() {
        return (int)1L;
    }
    public static int ATTR_FILE_TOTALSIZE() {
        return (int)2L;
    }
    public static int ATTR_FILE_ALLOCSIZE() {
        return (int)4L;
    }
    public static int ATTR_FILE_IOBLOCKSIZE() {
        return (int)8L;
    }
    public static int ATTR_FILE_DEVTYPE() {
        return (int)32L;
    }
    public static int ATTR_FILE_FORKCOUNT() {
        return (int)128L;
    }
    public static int ATTR_FILE_FORKLIST() {
        return (int)256L;
    }
    public static int ATTR_FILE_DATALENGTH() {
        return (int)512L;
    }
    public static int ATTR_FILE_DATAALLOCSIZE() {
        return (int)1024L;
    }
    public static int ATTR_FILE_RSRCLENGTH() {
        return (int)4096L;
    }
    public static int ATTR_FILE_RSRCALLOCSIZE() {
        return (int)8192L;
    }
    public static int ATTR_FILE_VALIDMASK() {
        return (int)14335L;
    }
    public static int ATTR_FILE_SETMASK() {
        return (int)32L;
    }
    public static int ATTR_CMNEXT_RELPATH() {
        return (int)4L;
    }
    public static int ATTR_CMNEXT_PRIVATESIZE() {
        return (int)8L;
    }
    public static int ATTR_CMNEXT_LINKID() {
        return (int)16L;
    }
    public static int ATTR_CMNEXT_NOFIRMLINKPATH() {
        return (int)32L;
    }
    public static int ATTR_CMNEXT_REALDEVID() {
        return (int)64L;
    }
    public static int ATTR_CMNEXT_REALFSID() {
        return (int)128L;
    }
    public static int ATTR_CMNEXT_CLONEID() {
        return (int)256L;
    }
    public static int ATTR_CMNEXT_EXT_FLAGS() {
        return (int)512L;
    }
    public static int ATTR_CMNEXT_RECURSIVE_GENCOUNT() {
        return (int)1024L;
    }
    public static int ATTR_CMNEXT_VALIDMASK() {
        return (int)2044L;
    }
    public static int ATTR_CMNEXT_SETMASK() {
        return (int)0L;
    }
    public static int ATTR_FORK_TOTALSIZE() {
        return (int)1L;
    }
    public static int ATTR_FORK_ALLOCSIZE() {
        return (int)2L;
    }
    public static int ATTR_FORK_VALIDMASK() {
        return (int)3L;
    }
    public static int ATTR_FORK_SETMASK() {
        return (int)0L;
    }
    public static int ATTR_CMN_NAMEDATTRCOUNT() {
        return (int)524288L;
    }
    public static int ATTR_CMN_NAMEDATTRLIST() {
        return (int)1048576L;
    }
    public static int ATTR_FILE_CLUMPSIZE() {
        return (int)16L;
    }
    public static int ATTR_FILE_FILETYPE() {
        return (int)64L;
    }
    public static int ATTR_FILE_DATAEXTENTS() {
        return (int)2048L;
    }
    public static int ATTR_FILE_RSRCEXTENTS() {
        return (int)16384L;
    }
    public static int SRCHFS_START() {
        return (int)1L;
    }
    public static int SRCHFS_MATCHPARTIALNAMES() {
        return (int)2L;
    }
    public static int SRCHFS_MATCHDIRS() {
        return (int)4L;
    }
    public static int SRCHFS_MATCHFILES() {
        return (int)8L;
    }
    public static int SRCHFS_SKIPLINKS() {
        return (int)16L;
    }
    public static int SRCHFS_SKIPINVISIBLE() {
        return (int)32L;
    }
    public static int SRCHFS_SKIPPACKAGES() {
        return (int)64L;
    }
    public static int SRCHFS_SKIPINAPPROPRIATE() {
        return (int)128L;
    }
    public static int MFSNAMELEN() {
        return (int)15L;
    }
    public static int MFSTYPENAMELEN() {
        return (int)16L;
    }
    public static int MNT_EXT_ROOT_DATA_VOL() {
        return (int)1L;
    }
    public static int MNT_RDONLY() {
        return (int)1L;
    }
    public static int MNT_SYNCHRONOUS() {
        return (int)2L;
    }
    public static int MNT_NOEXEC() {
        return (int)4L;
    }
    public static int MNT_NOSUID() {
        return (int)8L;
    }
    public static int MNT_NODEV() {
        return (int)16L;
    }
    public static int MNT_UNION() {
        return (int)32L;
    }
    public static int MNT_ASYNC() {
        return (int)64L;
    }
    public static int MNT_CPROTECT() {
        return (int)128L;
    }
    public static int MNT_EXPORTED() {
        return (int)256L;
    }
    public static int MNT_REMOVABLE() {
        return (int)512L;
    }
    public static int MNT_QUARANTINE() {
        return (int)1024L;
    }
    public static int MNT_LOCAL() {
        return (int)4096L;
    }
    public static int MNT_QUOTA() {
        return (int)8192L;
    }
    public static int MNT_ROOTFS() {
        return (int)16384L;
    }
    public static int MNT_DOVOLFS() {
        return (int)32768L;
    }
    public static int MNT_DONTBROWSE() {
        return (int)1048576L;
    }
    public static int MNT_IGNORE_OWNERSHIP() {
        return (int)2097152L;
    }
    public static int MNT_AUTOMOUNTED() {
        return (int)4194304L;
    }
    public static int MNT_JOURNALED() {
        return (int)8388608L;
    }
    public static int MNT_NOUSERXATTR() {
        return (int)16777216L;
    }
    public static int MNT_DEFWRITE() {
        return (int)33554432L;
    }
    public static int MNT_MULTILABEL() {
        return (int)67108864L;
    }
    public static int MNT_NOFOLLOW() {
        return (int)134217728L;
    }
    public static int MNT_NOATIME() {
        return (int)268435456L;
    }
    public static int MNT_SNAPSHOT() {
        return (int)1073741824L;
    }
    public static int MNT_UPDATE() {
        return (int)65536L;
    }
    public static int MNT_NOBLOCK() {
        return (int)131072L;
    }
    public static int MNT_RELOAD() {
        return (int)262144L;
    }
    public static int MNT_FORCE() {
        return (int)524288L;
    }
    public static int VFS_GENERIC() {
        return (int)0L;
    }
    public static int VFS_NUMMNTOPS() {
        return (int)1L;
    }
    public static int VFS_MAXTYPENUM() {
        return (int)1L;
    }
    public static int VFS_CONF() {
        return (int)2L;
    }
    public static int MNT_WAIT() {
        return (int)1L;
    }
    public static int MNT_NOWAIT() {
        return (int)2L;
    }
    public static int MNT_DWAIT() {
        return (int)4L;
    }
    public static int VFS_CTL_VERS1() {
        return (int)1L;
    }
    public static int VFS_CTL_OSTATFS() {
        return (int)65537L;
    }
    public static int VFS_CTL_UMOUNT() {
        return (int)65538L;
    }
    public static int VFS_CTL_QUERY() {
        return (int)65539L;
    }
    public static int VFS_CTL_NEWADDR() {
        return (int)65540L;
    }
    public static int VFS_CTL_TIMEO() {
        return (int)65541L;
    }
    public static int VFS_CTL_NOLOCKS() {
        return (int)65542L;
    }
    public static int VFS_CTL_SADDR() {
        return (int)65543L;
    }
    public static int VFS_CTL_DISC() {
        return (int)65544L;
    }
    public static int VFS_CTL_SERVERINFO() {
        return (int)65545L;
    }
    public static int VFS_CTL_NSTATUS() {
        return (int)65546L;
    }
    public static int VFS_CTL_STATFS64() {
        return (int)65547L;
    }
    public static int VQ_NOTRESP() {
        return (int)1L;
    }
    public static int VQ_NEEDAUTH() {
        return (int)2L;
    }
    public static int VQ_LOWDISK() {
        return (int)4L;
    }
    public static int VQ_MOUNT() {
        return (int)8L;
    }
    public static int VQ_UNMOUNT() {
        return (int)16L;
    }
    public static int VQ_DEAD() {
        return (int)32L;
    }
    public static int VQ_ASSIST() {
        return (int)64L;
    }
    public static int VQ_NOTRESPLOCK() {
        return (int)128L;
    }
    public static int VQ_UPDATE() {
        return (int)256L;
    }
    public static int VQ_VERYLOWDISK() {
        return (int)512L;
    }
}


