// Generated by jextract

package org.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class mach_service_port_info {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(255, Constants$root.C_CHAR$LAYOUT).withName("mspi_string_name"),
        Constants$root.C_CHAR$LAYOUT.withName("mspi_domain_type")
    ).withName("mach_service_port_info");
    public static MemoryLayout $LAYOUT() {
        return mach_service_port_info.$struct$LAYOUT;
    }
    public static MemorySegment mspi_string_name$slice(MemorySegment seg) {
        return seg.asSlice(0, 255);
    }
    static final VarHandle mspi_domain_type$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("mspi_domain_type"));
    public static VarHandle mspi_domain_type$VH() {
        return mach_service_port_info.mspi_domain_type$VH;
    }
    public static byte mspi_domain_type$get(MemorySegment seg) {
        return (byte)mach_service_port_info.mspi_domain_type$VH.get(seg);
    }
    public static void mspi_domain_type$set( MemorySegment seg, byte x) {
        mach_service_port_info.mspi_domain_type$VH.set(seg, x);
    }
    public static byte mspi_domain_type$get(MemorySegment seg, long index) {
        return (byte)mach_service_port_info.mspi_domain_type$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void mspi_domain_type$set(MemorySegment seg, long index, byte x) {
        mach_service_port_info.mspi_domain_type$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


