// Generated by jextract

package org.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class mach_port_qos {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            MemoryLayout.paddingLayout(1).withName("name"),
            MemoryLayout.paddingLayout(1).withName("prealloc"),
            MemoryLayout.paddingLayout(30).withName("pad1")
        ),
        Constants$root.C_INT$LAYOUT.withName("len")
    ).withName("mach_port_qos");
    public static MemoryLayout $LAYOUT() {
        return mach_port_qos.$struct$LAYOUT;
    }
    static final VarHandle len$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("len"));
    public static VarHandle len$VH() {
        return mach_port_qos.len$VH;
    }
    public static int len$get(MemorySegment seg) {
        return (int)mach_port_qos.len$VH.get(seg);
    }
    public static void len$set( MemorySegment seg, int x) {
        mach_port_qos.len$VH.set(seg, x);
    }
    public static int len$get(MemorySegment seg, long index) {
        return (int)mach_port_qos.len$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void len$set(MemorySegment seg, long index, int x) {
        mach_port_qos.len$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


