// Generated by jextract

package org.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public interface os_function_t {

    void apply(java.lang.foreign.MemoryAddress _x0);
    static MemorySegment allocate(os_function_t fi, MemorySession session) {
        return RuntimeHelper.upcallStub(os_function_t.class, fi, constants$22.os_function_t$FUNC, session);
    }
    static os_function_t ofAddress(MemoryAddress addr, MemorySession session) {
        MemorySegment symbol = MemorySegment.ofAddress(addr, 0, session);
        return (java.lang.foreign.MemoryAddress __x0) -> {
            try {
                constants$23.os_function_t$MH.invokeExact((Addressable)symbol, (java.lang.foreign.Addressable)__x0);
            } catch (Throwable ex$) {
                throw new AssertionError("should not reach here", ex$);
            }
        };
    }
}


