// Generated by jextract

package org.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class statfs {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("f_bsize"),
        Constants$root.C_INT$LAYOUT.withName("f_iosize"),
        Constants$root.C_LONG_LONG$LAYOUT.withName("f_blocks"),
        Constants$root.C_LONG_LONG$LAYOUT.withName("f_bfree"),
        Constants$root.C_LONG_LONG$LAYOUT.withName("f_bavail"),
        Constants$root.C_LONG_LONG$LAYOUT.withName("f_files"),
        Constants$root.C_LONG_LONG$LAYOUT.withName("f_ffree"),
        MemoryLayout.structLayout(
            MemoryLayout.sequenceLayout(2, Constants$root.C_INT$LAYOUT).withName("val")
        ).withName("f_fsid"),
        Constants$root.C_INT$LAYOUT.withName("f_owner"),
        Constants$root.C_INT$LAYOUT.withName("f_type"),
        Constants$root.C_INT$LAYOUT.withName("f_flags"),
        Constants$root.C_INT$LAYOUT.withName("f_fssubtype"),
        MemoryLayout.sequenceLayout(16, Constants$root.C_CHAR$LAYOUT).withName("f_fstypename"),
        MemoryLayout.sequenceLayout(1024, Constants$root.C_CHAR$LAYOUT).withName("f_mntonname"),
        MemoryLayout.sequenceLayout(1024, Constants$root.C_CHAR$LAYOUT).withName("f_mntfromname"),
        Constants$root.C_INT$LAYOUT.withName("f_flags_ext"),
        MemoryLayout.sequenceLayout(7, Constants$root.C_INT$LAYOUT).withName("f_reserved")
    ).withName("statfs");
    public static MemoryLayout $LAYOUT() {
        return statfs.$struct$LAYOUT;
    }
    static final VarHandle f_bsize$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("f_bsize"));
    public static VarHandle f_bsize$VH() {
        return statfs.f_bsize$VH;
    }
    public static int f_bsize$get(MemorySegment seg) {
        return (int)statfs.f_bsize$VH.get(seg);
    }
    public static void f_bsize$set( MemorySegment seg, int x) {
        statfs.f_bsize$VH.set(seg, x);
    }
    public static int f_bsize$get(MemorySegment seg, long index) {
        return (int)statfs.f_bsize$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void f_bsize$set(MemorySegment seg, long index, int x) {
        statfs.f_bsize$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle f_iosize$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("f_iosize"));
    public static VarHandle f_iosize$VH() {
        return statfs.f_iosize$VH;
    }
    public static int f_iosize$get(MemorySegment seg) {
        return (int)statfs.f_iosize$VH.get(seg);
    }
    public static void f_iosize$set( MemorySegment seg, int x) {
        statfs.f_iosize$VH.set(seg, x);
    }
    public static int f_iosize$get(MemorySegment seg, long index) {
        return (int)statfs.f_iosize$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void f_iosize$set(MemorySegment seg, long index, int x) {
        statfs.f_iosize$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle f_blocks$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("f_blocks"));
    public static VarHandle f_blocks$VH() {
        return statfs.f_blocks$VH;
    }
    public static long f_blocks$get(MemorySegment seg) {
        return (long)statfs.f_blocks$VH.get(seg);
    }
    public static void f_blocks$set( MemorySegment seg, long x) {
        statfs.f_blocks$VH.set(seg, x);
    }
    public static long f_blocks$get(MemorySegment seg, long index) {
        return (long)statfs.f_blocks$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void f_blocks$set(MemorySegment seg, long index, long x) {
        statfs.f_blocks$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle f_bfree$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("f_bfree"));
    public static VarHandle f_bfree$VH() {
        return statfs.f_bfree$VH;
    }
    public static long f_bfree$get(MemorySegment seg) {
        return (long)statfs.f_bfree$VH.get(seg);
    }
    public static void f_bfree$set( MemorySegment seg, long x) {
        statfs.f_bfree$VH.set(seg, x);
    }
    public static long f_bfree$get(MemorySegment seg, long index) {
        return (long)statfs.f_bfree$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void f_bfree$set(MemorySegment seg, long index, long x) {
        statfs.f_bfree$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle f_bavail$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("f_bavail"));
    public static VarHandle f_bavail$VH() {
        return statfs.f_bavail$VH;
    }
    public static long f_bavail$get(MemorySegment seg) {
        return (long)statfs.f_bavail$VH.get(seg);
    }
    public static void f_bavail$set( MemorySegment seg, long x) {
        statfs.f_bavail$VH.set(seg, x);
    }
    public static long f_bavail$get(MemorySegment seg, long index) {
        return (long)statfs.f_bavail$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void f_bavail$set(MemorySegment seg, long index, long x) {
        statfs.f_bavail$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle f_files$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("f_files"));
    public static VarHandle f_files$VH() {
        return statfs.f_files$VH;
    }
    public static long f_files$get(MemorySegment seg) {
        return (long)statfs.f_files$VH.get(seg);
    }
    public static void f_files$set( MemorySegment seg, long x) {
        statfs.f_files$VH.set(seg, x);
    }
    public static long f_files$get(MemorySegment seg, long index) {
        return (long)statfs.f_files$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void f_files$set(MemorySegment seg, long index, long x) {
        statfs.f_files$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle f_ffree$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("f_ffree"));
    public static VarHandle f_ffree$VH() {
        return statfs.f_ffree$VH;
    }
    public static long f_ffree$get(MemorySegment seg) {
        return (long)statfs.f_ffree$VH.get(seg);
    }
    public static void f_ffree$set( MemorySegment seg, long x) {
        statfs.f_ffree$VH.set(seg, x);
    }
    public static long f_ffree$get(MemorySegment seg, long index) {
        return (long)statfs.f_ffree$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void f_ffree$set(MemorySegment seg, long index, long x) {
        statfs.f_ffree$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment f_fsid$slice(MemorySegment seg) {
        return seg.asSlice(48, 8);
    }
    static final VarHandle f_owner$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("f_owner"));
    public static VarHandle f_owner$VH() {
        return statfs.f_owner$VH;
    }
    public static int f_owner$get(MemorySegment seg) {
        return (int)statfs.f_owner$VH.get(seg);
    }
    public static void f_owner$set( MemorySegment seg, int x) {
        statfs.f_owner$VH.set(seg, x);
    }
    public static int f_owner$get(MemorySegment seg, long index) {
        return (int)statfs.f_owner$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void f_owner$set(MemorySegment seg, long index, int x) {
        statfs.f_owner$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle f_type$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("f_type"));
    public static VarHandle f_type$VH() {
        return statfs.f_type$VH;
    }
    public static int f_type$get(MemorySegment seg) {
        return (int)statfs.f_type$VH.get(seg);
    }
    public static void f_type$set( MemorySegment seg, int x) {
        statfs.f_type$VH.set(seg, x);
    }
    public static int f_type$get(MemorySegment seg, long index) {
        return (int)statfs.f_type$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void f_type$set(MemorySegment seg, long index, int x) {
        statfs.f_type$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle f_flags$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("f_flags"));
    public static VarHandle f_flags$VH() {
        return statfs.f_flags$VH;
    }
    public static int f_flags$get(MemorySegment seg) {
        return (int)statfs.f_flags$VH.get(seg);
    }
    public static void f_flags$set( MemorySegment seg, int x) {
        statfs.f_flags$VH.set(seg, x);
    }
    public static int f_flags$get(MemorySegment seg, long index) {
        return (int)statfs.f_flags$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void f_flags$set(MemorySegment seg, long index, int x) {
        statfs.f_flags$VH.set(seg.asSlice(index*sizeof()), x);
    }
    static final VarHandle f_fssubtype$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("f_fssubtype"));
    public static VarHandle f_fssubtype$VH() {
        return statfs.f_fssubtype$VH;
    }
    public static int f_fssubtype$get(MemorySegment seg) {
        return (int)statfs.f_fssubtype$VH.get(seg);
    }
    public static void f_fssubtype$set( MemorySegment seg, int x) {
        statfs.f_fssubtype$VH.set(seg, x);
    }
    public static int f_fssubtype$get(MemorySegment seg, long index) {
        return (int)statfs.f_fssubtype$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void f_fssubtype$set(MemorySegment seg, long index, int x) {
        statfs.f_fssubtype$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment f_fstypename$slice(MemorySegment seg) {
        return seg.asSlice(72, 16);
    }
    public static MemorySegment f_mntonname$slice(MemorySegment seg) {
        return seg.asSlice(88, 1024);
    }
    public static MemorySegment f_mntfromname$slice(MemorySegment seg) {
        return seg.asSlice(1112, 1024);
    }
    static final VarHandle f_flags_ext$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("f_flags_ext"));
    public static VarHandle f_flags_ext$VH() {
        return statfs.f_flags_ext$VH;
    }
    public static int f_flags_ext$get(MemorySegment seg) {
        return (int)statfs.f_flags_ext$VH.get(seg);
    }
    public static void f_flags_ext$set( MemorySegment seg, int x) {
        statfs.f_flags_ext$VH.set(seg, x);
    }
    public static int f_flags_ext$get(MemorySegment seg, long index) {
        return (int)statfs.f_flags_ext$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void f_flags_ext$set(MemorySegment seg, long index, int x) {
        statfs.f_flags_ext$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment f_reserved$slice(MemorySegment seg) {
        return seg.asSlice(2140, 28);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


