// Generated by jextract

package org.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class vfs_server {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("vs_minutes"),
        MemoryLayout.sequenceLayout(768, Constants$root.C_CHAR$LAYOUT).withName("vs_server_name")
    ).withName("vfs_server");
    public static MemoryLayout $LAYOUT() {
        return vfs_server.$struct$LAYOUT;
    }
    static final VarHandle vs_minutes$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("vs_minutes"));
    public static VarHandle vs_minutes$VH() {
        return vfs_server.vs_minutes$VH;
    }
    public static int vs_minutes$get(MemorySegment seg) {
        return (int)vfs_server.vs_minutes$VH.get(seg);
    }
    public static void vs_minutes$set( MemorySegment seg, int x) {
        vfs_server.vs_minutes$VH.set(seg, x);
    }
    public static int vs_minutes$get(MemorySegment seg, long index) {
        return (int)vfs_server.vs_minutes$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void vs_minutes$set(MemorySegment seg, long index, int x) {
        vfs_server.vs_minutes$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment vs_server_name$slice(MemorySegment seg) {
        return seg.asSlice(4, 768);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


