// Generated by jextract

package org.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class vfsquery {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        Constants$root.C_INT$LAYOUT.withName("vq_flags"),
        MemoryLayout.sequenceLayout(31, Constants$root.C_INT$LAYOUT).withName("vq_spare")
    ).withName("vfsquery");
    public static MemoryLayout $LAYOUT() {
        return vfsquery.$struct$LAYOUT;
    }
    static final VarHandle vq_flags$VH = $struct$LAYOUT.varHandle(MemoryLayout.PathElement.groupElement("vq_flags"));
    public static VarHandle vq_flags$VH() {
        return vfsquery.vq_flags$VH;
    }
    public static int vq_flags$get(MemorySegment seg) {
        return (int)vfsquery.vq_flags$VH.get(seg);
    }
    public static void vq_flags$set( MemorySegment seg, int x) {
        vfsquery.vq_flags$VH.set(seg, x);
    }
    public static int vq_flags$get(MemorySegment seg, long index) {
        return (int)vfsquery.vq_flags$VH.get(seg.asSlice(index*sizeof()));
    }
    public static void vq_flags$set(MemorySegment seg, long index, int x) {
        vfsquery.vq_flags$VH.set(seg.asSlice(index*sizeof()), x);
    }
    public static MemorySegment vq_spare$slice(MemorySegment seg) {
        return seg.asSlice(4, 124);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


