// Generated by jextract

package org.fuse;

import java.lang.invoke.MethodHandle;
import java.lang.invoke.VarHandle;
import java.nio.ByteOrder;
import java.lang.foreign.*;
import static java.lang.foreign.ValueLayout.*;
public class vol_attributes_attr {

    static final  GroupLayout $struct$LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.structLayout(
            Constants$root.C_INT$LAYOUT.withName("commonattr"),
            Constants$root.C_INT$LAYOUT.withName("volattr"),
            Constants$root.C_INT$LAYOUT.withName("dirattr"),
            Constants$root.C_INT$LAYOUT.withName("fileattr"),
            Constants$root.C_INT$LAYOUT.withName("forkattr")
        ).withName("validattr"),
        MemoryLayout.structLayout(
            Constants$root.C_INT$LAYOUT.withName("commonattr"),
            Constants$root.C_INT$LAYOUT.withName("volattr"),
            Constants$root.C_INT$LAYOUT.withName("dirattr"),
            Constants$root.C_INT$LAYOUT.withName("fileattr"),
            Constants$root.C_INT$LAYOUT.withName("forkattr")
        ).withName("nativeattr")
    ).withName("vol_attributes_attr");
    public static MemoryLayout $LAYOUT() {
        return vol_attributes_attr.$struct$LAYOUT;
    }
    public static MemorySegment validattr$slice(MemorySegment seg) {
        return seg.asSlice(0, 20);
    }
    public static MemorySegment nativeattr$slice(MemorySegment seg) {
        return seg.asSlice(20, 20);
    }
    public static long sizeof() { return $LAYOUT().byteSize(); }
    public static MemorySegment allocate(SegmentAllocator allocator) { return allocator.allocate($LAYOUT()); }
    public static MemorySegment allocateArray(int len, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(len, $LAYOUT()));
    }
    public static MemorySegment ofAddress(MemoryAddress addr, MemorySession session) { return RuntimeHelper.asArray(addr, $LAYOUT(), 1, session); }
}


